# Multiple regression {#mult-reg}

```{block2, type="uptohere", echo=TRUE}
The content in this chapter is currently just placeholder. We will remove this banner once the chapter content has been updated and ready for review.
```

<!-- Example from: https://holtzy.github.io/Pimp-my-rmd/ - interactive graphic! -->
<!-- ```{r} -->
<!-- library(ggplot2) -->
<!-- library(plotly) -->
<!-- library(gapminder) -->

<!-- p <- gapminder %>% -->
<!--   filter(year==1977) %>% -->
<!--   ggplot( aes(gdpPercap, lifeExp, size = pop, color=continent)) + -->
<!--   geom_point() + -->
<!--   scale_x_log10() + -->
<!--   theme_bw() -->

<!-- ggplotly(p) -->
<!-- ``` -->

## Num vs. whatever - MLR

- Introduction to multiple regression

## Parallel slopes

## Hint at interaction, planes, and parallel planes but not quantify

- Visualization of higher-dimensional models (rgl demo)



## `R`: Multiple and logistic regression

### Interactive R tutorials

Navigate the concepts you've learned in this chapter in R using the following self-paced tutorials. 
All you need is your browser to get started!

::: {.alltutorials}
[Tutorial 4: Multiple and logistic regression](https://openintrostat.github.io/ims-tutorials/04-multivariable-and-logistic-models/)
:::

::: {.singletutorial}
[Tutorial 4 - Lesson 1: Parallel slopes](https://openintro.shinyapps.io/ims-04-multivariable-and-logistic-models-01/)
:::

::: {.singletutorial}
[Tutorial 4 - Lesson 2: Evaluating and extending parallel slopes model](https://openintro.shinyapps.io/ims-04-multivariable-and-logistic-models-02/)
:::

::: {.singletutorial}
[Tutorial 4 - Lesson 3: Multiple regression](https://openintro.shinyapps.io/ims-04-multivariable-and-logistic-models-03/)
:::

::: {.singletutorial}
[Tutorial 4 - Lesson 4: Logistic regression](https://openintro.shinyapps.io/ims-04-multivariable-and-logistic-models-04/)
:::

::: {.singletutorial}
[Tutorial 4 - Lesson 5: Case study - Italian restaurants in NYC](https://openintro.shinyapps.io/ims-04-multivariable-and-logistic-models-05/)
:::

You can also access the full list of tutorials supporting this book [here](https://openintrostat.github.io/ims-tutorials/).

### R labs

Further apply the concepts you've learned in this chapter in R with computational labs that walk you through a data analysis case study.

::: {.singlelab}
[Multiple linear regression - Grading the professor](http://openintrostat.github.io/oilabs-tidy/09_multiple_regression/multiple_regression.html)
:::

::: {.alllabs}
[Full list of labs supporting OpenIntro::Introduction to Modern Statistics](http://openintrostat.github.io/oilabs-tidy/)
:::


## Chapter 4 review {#chp4-review}

### Terms

We introduced the following terms in the chapter. 
If you're not sure what some of these terms mean, we recommend you go back in the text and review their definitions.
We are purposefully presenting them in alphabetical order, instead of in order of appearance, so they will be a little more challenging to locate. 
However you should be able to easily spot them as **bolded text**.

```{r eval = FALSE}
make_terms_table(terms_chp_4)
```
