# Appendix: Activities {#activities}

Each week, you will work through an in-class activity with your team mates and the guidance of your instructor. We recommend you purchase a printed copy of the activity coursepack from the MSU Bookstore and bring this to class each day. If you cannot purchase the printed coursepack, you may print and activities from this Appendix and bring them to class with you.


| Activity | Title | Content |
|--	|:-------- |:-------------	|
| 1 | [Martian Alphabet](activities/01-MartianAlphabet.pdf) | Introduction to inference |
| 2 | [Study Design](activities/02-StudyDesign.pdf) | Sampling bias, experiments, observational studies, and confounding variables |
| 3 | [Current Population Survey](activities/03-CPS.pdf) | Exploratory data analysis: categorical variables |
| 4 | [IMDb Movie Reviews](activities/04-IMDbMovieReviews.pdf) | Exploratory data analysis: quantitative variables |
| 5 | [Movie Profits](activities/05-MovieProfits.pdf) | Exploratory data analysis: regression and multivariate thinking  |
| 6 | [Handedness of Male Boxers](activities/06-MaleBoxers.pdf) | Inference: one proportion |
| 7 | [Winter Sports Helmet Use and Head Injuries](activities/07-HelmetUse.pdf) | Inference: difference in proportions |
| 8 | [COVID-19 and Air Pollution](activities/08-COVID.pdf) | Inference: paired mean difference |
| 9 | [Weather Patterns and Record Snowfall](activities/09-Snowfall.pdf) | Inference: difference in means |
| 10 | [Hand Dexterity](activities/10-HandDexterity.pdf) | Inference: regression |
