# Turning data into knowledge {#summary}

> Statistical thinking will one day be as necessary for efficient citizenship as the ability to read and write. – H. G. Wells, 1903

## Choosing an appropriate procedure

```{block2, type="todo", echo=TRUE}
- golden ticket
```

## Ten guiding principles

Past president of the American Statistical Association Jessica Utts^[To learn more about Dr. Utts, read Allan Rossman's [Interview with Jessica Utts](http://jse.amstat.org/v22n2/rossmanint.pdf) in the _Journal of Statistics Education_.],
one of the leaders in Statistics Education research, is a strong advocate for statistical literacy for all. In her textbook _Mind on Statistics @MOS and article _What Educated Citizens Should Know About Statistics and Probability_ @utts2003, she lays out her guiding principles for how everyone should interact with data and the world. The following principles are adapted from those sources.


<!-- Mind on Statistics (p. 683) -->
<!-- A representative sample can be used to make inferences about a larger population, -->
<!-- but descriptive statistics are the only useful results for an unrepresentative -->
<!-- sample. -->
<!-- 2. Cause and effect can be inferred from randomized experiments but generally -->
<!-- not from observational studies, in which confounding variables are likely to -->
<!-- cloud the interpretation. -->
<!-- 3. A conservative estimate of sampling error in a survey is the margin of error, -->
<!-- 1/"n. This value provides an upper bound on the difference between the -->
<!-- true proportion and the sample proportion that holds for at least 95% of -->
<!-- properly conducted surveys. -->
<!-- 4. The margin of error does not include nonsampling error, such as errors due -->
<!-- to biased wording, nonresponse, and so on. -->
<!-- 5. When the individuals measured constitute the whole population, there is no -->
<!-- need for statistical inference because the truth is known. -->
<!-- 6. A significance test based on a very large sample is likely to produce a statistically -->
<!-- significant result even if the true value is close to the null value. In such -->
<!-- cases, it is wise to estimate the magnitude of the parameter with a confidence -->
<!-- interval to determine whether the result has practical importance. -->
<!-- 7. A significance test based on a small sample may not produce a statistically -->
<!-- significant result even if the true value differs substantially from the null -->
<!-- value. Because this is so, it is important that the null hypothesis not be “accepted,” -->
<!-- even when we don’t have enough evidence to reject it. -->
<!-- 8. When deciding how readily to reject the null hypothesis (what significance -->
<!-- level to use), it is important to consider the consequences of Type 1 and Type -->
<!-- 2 errors. If a Type 1 error has serious consequences, the level of significance -->
<!-- should be small. If a Type 2 error is more serious, a higher level of significance -->
<!-- should be used. -->
<!-- 9. A study that examines many hypotheses could find one or more statistically -->
<!-- significant results just by chance, so you should try to find out how many -->
<!-- tests were conducted when you read about a significant result. For instance, -->
<!-- with a level of significance of .05, about 1 test in 20 will result in statistical -->
<!-- significance when all of the null hypotheses are correct and the tests are independent. -->
<!-- It is common in large studies to find that one test attracts media -->
<!-- attention, so it is important to know whether that test was the only one out of -->
<!-- many conducted that achieved statistical significance. -->
<!-- 10. You will sometimes read that researchers were surprised to find “no effect” -->
<!-- and that a study “failed to replicate” an earlier finding of statistical significance. -->
<!-- In that case, consider two possible explanations. One is that the sample -->
<!-- size was too small and the test had low power. The other possibility is -->
<!-- that the result in the first study was based on a Type 1 error. This explanation -->
<!-- is particularly likely if the effect in that study was moderate and was part of a -->
<!-- larger study that covered multiple hypotheses. -->


<!-- TAS Article: -->
<!-- 1. When it can be concludedthat a relationshipis one of cause -->
<!-- and effect, and when it cannot, including the difference between -->
<!-- randomized experiments and observational studies. -->
<!-- 2. The difference between statistical signi"cance and practical -->
<!-- importance, especially when using large sample sizes. -->
<!-- 3. The difference between "nding “no effect” or “no difference” -->
<!-- and "nding no statistically signi"cant effect or difference, -->
<!-- especially when using small sample sizes. -->
<!-- 4. Common sources of bias in surveys and experiments, such -->
<!-- as poor wording of questions, volunteer response, and socially -->
<!-- desirable answers. -->
<!-- 5. The idea that coincidencesand seemingly very improbable -->
<!-- events are not uncommon because there are so many possibilities. -->
<!-- 6. “Confusionof the inverse” inwhicha conditionalprobability -->
<!-- in one direction is confused with the conditional probability -->
<!-- in the other direction. -->
<!-- 7. Understandingthat variability is natural, and that “normal” -->
<!-- is not the same as “average.” -->
