<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 6 Inference for quantitative data | Montana State Introductory Statistics with R</title>
  <meta name="description" content="Open resources textbook for Stat 216 at Montana State University" />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 6 Inference for quantitative data | Montana State Introductory Statistics with R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Open resources textbook for Stat 216 at Montana State University" />
  <meta name="github-repo" content="MTstateIntroStats/IntroStatTextbook" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 6 Inference for quantitative data | Montana State Introductory Statistics with R" />
  
  <meta name="twitter:description" content="Open resources textbook for Stat 216 at Montana State University" />
  

<meta name="author" content="Nicole Carnegie, Stacey Hancock, Elijah Meyer, Jade Schmidt, Melinda Yager" />


<meta name="date" content="2020-09-10" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="inference-cat.html"/>
<link rel="next" href="inference-reg.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.5.1/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.9.2.1/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.1.0.1/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.1.0.1/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.52.2/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.52.2/plotly-latest.min.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="css\oistyle.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">MSU Intro Stat with R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#textbook-overview"><i class="fa fa-check"></i>Textbook overview</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#statistical-computing"><i class="fa fa-check"></i>Statistical computing</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#getting-rstudio"><i class="fa fa-check"></i>Getting RStudio</a></li>
<li><a href="index.html#installing-catstats">Installing <code>catstats</code></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i>Acknowledgements</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="about-the-authors.html"><a href="about-the-authors.html"><i class="fa fa-check"></i>About the Authors</a><ul>
<li class="chapter" data-level="" data-path="about-the-authors.html"><a href="about-the-authors.html#montana-state-university-authors"><i class="fa fa-check"></i>Montana State University Authors</a></li>
<li class="chapter" data-level="" data-path="about-the-authors.html"><a href="about-the-authors.html#openintro-authors"><i class="fa fa-check"></i>OpenIntro Authors</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="copyright.html"><a href="copyright.html"><i class="fa fa-check"></i>Copyright</a></li>
<li class="chapter" data-level="1" data-path="intro-to-data.html"><a href="intro-to-data.html"><i class="fa fa-check"></i><b>1</b> Introduction to data</a><ul>
<li class="chapter" data-level="1.1" data-path="intro-to-data.html"><a href="intro-to-data.html#basic-stents-strokes"><i class="fa fa-check"></i><b>1.1</b> Case study: using stents to prevent strokes</a></li>
<li class="chapter" data-level="1.2" data-path="intro-to-data.html"><a href="intro-to-data.html#data-basics"><i class="fa fa-check"></i><b>1.2</b> Data basics</a><ul>
<li class="chapter" data-level="1.2.1" data-path="intro-to-data.html"><a href="intro-to-data.html#observations-variables-and-data-frames"><i class="fa fa-check"></i><b>1.2.1</b> Observations, variables, and data frames</a></li>
<li class="chapter" data-level="1.2.2" data-path="intro-to-data.html"><a href="intro-to-data.html#variable-types"><i class="fa fa-check"></i><b>1.2.2</b> Types of variables</a></li>
<li class="chapter" data-level="1.2.3" data-path="intro-to-data.html"><a href="intro-to-data.html#variable-relations"><i class="fa fa-check"></i><b>1.2.3</b> Relationships between variables</a></li>
<li class="chapter" data-level="1.2.4" data-path="intro-to-data.html"><a href="intro-to-data.html#explanatory-and-response-variables"><i class="fa fa-check"></i><b>1.2.4</b> Explanatory and response variables</a></li>
<li class="chapter" data-level="1.2.5" data-path="intro-to-data.html"><a href="intro-to-data.html#introducing-observational-studies-and-experiments"><i class="fa fa-check"></i><b>1.2.5</b> Introducing observational studies and experiments</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="intro-to-data.html"><a href="intro-to-data.html#sampling-principles-strategies"><i class="fa fa-check"></i><b>1.3</b> Sampling principles and strategies</a><ul>
<li class="chapter" data-level="1.3.1" data-path="intro-to-data.html"><a href="intro-to-data.html#populations-and-samples"><i class="fa fa-check"></i><b>1.3.1</b> Populations and samples</a></li>
<li class="chapter" data-level="1.3.2" data-path="intro-to-data.html"><a href="intro-to-data.html#anecdotal-evidence"><i class="fa fa-check"></i><b>1.3.2</b> Anecdotal evidence</a></li>
<li class="chapter" data-level="1.3.3" data-path="intro-to-data.html"><a href="intro-to-data.html#sampling-from-a-population"><i class="fa fa-check"></i><b>1.3.3</b> Sampling from a population</a></li>
<li class="chapter" data-level="1.3.4" data-path="intro-to-data.html"><a href="intro-to-data.html#samp-methods"><i class="fa fa-check"></i><b>1.3.4</b> Four sampling methods (special topic)</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="intro-to-data.html"><a href="intro-to-data.html#observational-studies"><i class="fa fa-check"></i><b>1.4</b> Observational studies</a></li>
<li class="chapter" data-level="1.5" data-path="intro-to-data.html"><a href="intro-to-data.html#experiments"><i class="fa fa-check"></i><b>1.5</b> Experiments</a><ul>
<li class="chapter" data-level="1.5.1" data-path="intro-to-data.html"><a href="intro-to-data.html#principles-of-experimental-design"><i class="fa fa-check"></i><b>1.5.1</b> Principles of experimental design</a></li>
<li class="chapter" data-level="1.5.2" data-path="intro-to-data.html"><a href="intro-to-data.html#reducing-bias-human-experiments"><i class="fa fa-check"></i><b>1.5.2</b> Reducing bias in human experiments</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="intro-to-data.html"><a href="intro-to-data.html#scope-of-inference"><i class="fa fa-check"></i><b>1.6</b> Scope of inference</a></li>
<li class="chapter" data-level="1.7" data-path="intro-to-data.html"><a href="intro-to-data.html#data-in-r"><i class="fa fa-check"></i><b>1.7</b> Data in <code>R</code></a><ul>
<li class="chapter" data-level="1.7.1" data-path="intro-to-data.html"><a href="intro-to-data.html#dataframes-in-r"><i class="fa fa-check"></i><b>1.7.1</b> Dataframes in <code>R</code></a></li>
<li class="chapter" data-level="1.7.2" data-path="intro-to-data.html"><a href="intro-to-data.html#datastruc"><i class="fa fa-check"></i><b>1.7.2</b> Tidy structure of data</a></li>
<li class="chapter" data-level="1.7.3" data-path="intro-to-data.html"><a href="intro-to-data.html#using-the-pipe-to-chain"><i class="fa fa-check"></i><b>1.7.3</b> Using the pipe to chain</a></li>
<li class="chapter" data-level="1.7.4" data-path="intro-to-data.html"><a href="intro-to-data.html#interactive-r-tutorials"><i class="fa fa-check"></i><b>1.7.4</b> Interactive R tutorials</a></li>
<li class="chapter" data-level="1.7.5" data-path="intro-to-data.html"><a href="intro-to-data.html#r-labs"><i class="fa fa-check"></i><b>1.7.5</b> R labs</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="intro-to-data.html"><a href="intro-to-data.html#chp1-review"><i class="fa fa-check"></i><b>1.8</b> Chapter 1 review</a><ul>
<li class="chapter" data-level="1.8.1" data-path="intro-to-data.html"><a href="intro-to-data.html#terms"><i class="fa fa-check"></i><b>1.8.1</b> Terms</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="eda.html"><a href="eda.html"><i class="fa fa-check"></i><b>2</b> Exploratory data analysis</a><ul>
<li class="chapter" data-level="2.1" data-path="eda.html"><a href="eda.html#categorical-data"><i class="fa fa-check"></i><b>2.1</b> Exploring categorical data</a><ul>
<li class="chapter" data-level="2.1.1" data-path="eda.html"><a href="eda.html#contingency-tables-and-conditional-proportions"><i class="fa fa-check"></i><b>2.1.1</b> Contingency tables and conditional proportions</a></li>
<li class="chapter" data-level="2.1.2" data-path="eda.html"><a href="eda.html#bar-plots-and-mosaic-plots"><i class="fa fa-check"></i><b>2.1.2</b> Bar plots and mosaic plots</a></li>
<li class="chapter" data-level="2.1.3" data-path="eda.html"><a href="eda.html#why-not-pie-charts"><i class="fa fa-check"></i><b>2.1.3</b> Why not pie charts?</a></li>
<li class="chapter" data-level="2.1.4" data-path="eda.html"><a href="eda.html#simpsons-paradox"><i class="fa fa-check"></i><b>2.1.4</b> Simpson’s paradox</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="eda.html"><a href="eda.html#probability-with-tables"><i class="fa fa-check"></i><b>2.2</b> Probability with tables</a><ul>
<li class="chapter" data-level="2.2.1" data-path="eda.html"><a href="eda.html#defining-probability"><i class="fa fa-check"></i><b>2.2.1</b> Defining probability</a></li>
<li class="chapter" data-level="2.2.2" data-path="eda.html"><a href="eda.html#finding-probabilities-with-tables"><i class="fa fa-check"></i><b>2.2.2</b> Finding probabilities with tables</a></li>
<li class="chapter" data-level="2.2.3" data-path="eda.html"><a href="eda.html#probability-notation"><i class="fa fa-check"></i><b>2.2.3</b> Probability notation</a></li>
<li class="chapter" data-level="2.2.4" data-path="eda.html"><a href="eda.html#diagnostic-testing"><i class="fa fa-check"></i><b>2.2.4</b> Diagnostic testing</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="eda.html"><a href="eda.html#quantitative-data"><i class="fa fa-check"></i><b>2.3</b> Exploring quantitative data</a><ul>
<li class="chapter" data-level="2.3.1" data-path="eda.html"><a href="eda.html#scatterplots"><i class="fa fa-check"></i><b>2.3.1</b> Scatterplots for paired data</a></li>
<li class="chapter" data-level="2.3.2" data-path="eda.html"><a href="eda.html#dotplots"><i class="fa fa-check"></i><b>2.3.2</b> Dot plots and the mean</a></li>
<li class="chapter" data-level="2.3.3" data-path="eda.html"><a href="eda.html#histograms"><i class="fa fa-check"></i><b>2.3.3</b> Histograms and shape</a></li>
<li class="chapter" data-level="2.3.4" data-path="eda.html"><a href="eda.html#variance-sd"><i class="fa fa-check"></i><b>2.3.4</b> Variance and standard deviation</a></li>
<li class="chapter" data-level="2.3.5" data-path="eda.html"><a href="eda.html#box-plots-quartiles-and-the-median"><i class="fa fa-check"></i><b>2.3.5</b> Box plots, quartiles, and the median</a></li>
<li class="chapter" data-level="2.3.6" data-path="eda.html"><a href="eda.html#describing-and-comparing-quantitative-distributions"><i class="fa fa-check"></i><b>2.3.6</b> Describing and comparing quantitative distributions</a></li>
<li class="chapter" data-level="2.3.7" data-path="eda.html"><a href="eda.html#robust-statistics"><i class="fa fa-check"></i><b>2.3.7</b> Robust statistics</a></li>
<li class="chapter" data-level="2.3.8" data-path="eda.html"><a href="eda.html#transforming-data-special-topic"><i class="fa fa-check"></i><b>2.3.8</b> Transforming data (special topic)</a></li>
<li class="chapter" data-level="2.3.9" data-path="eda.html"><a href="eda.html#mapping-data-special-topic"><i class="fa fa-check"></i><b>2.3.9</b> Mapping data (special topic)</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="eda.html"><a href="eda.html#r-exploratory-data-analysis"><i class="fa fa-check"></i><b>2.4</b> <code>R</code>: Exploratory data analysis</a><ul>
<li class="chapter" data-level="2.4.1" data-path="intro-to-data.html"><a href="intro-to-data.html#interactive-r-tutorials"><i class="fa fa-check"></i><b>2.4.1</b> Interactive R tutorials</a></li>
<li class="chapter" data-level="2.4.2" data-path="intro-to-data.html"><a href="intro-to-data.html#r-labs"><i class="fa fa-check"></i><b>2.4.2</b> R labs</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="eda.html"><a href="eda.html#chp2-review"><i class="fa fa-check"></i><b>2.5</b> Chapter 2 review</a><ul>
<li class="chapter" data-level="2.5.1" data-path="eda.html"><a href="eda.html#notation-summary"><i class="fa fa-check"></i><b>2.5.1</b> Notation summary</a></li>
<li class="chapter" data-level="2.5.2" data-path="intro-to-data.html"><a href="intro-to-data.html#terms"><i class="fa fa-check"></i><b>2.5.2</b> Terms</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="cor-reg.html"><a href="cor-reg.html"><i class="fa fa-check"></i><b>3</b> Correlation and regression</a><ul>
<li class="chapter" data-level="3.1" data-path="cor-reg.html"><a href="cor-reg.html#fit-line-res-cor"><i class="fa fa-check"></i><b>3.1</b> Fitting a line, residuals, and correlation</a><ul>
<li class="chapter" data-level="3.1.1" data-path="cor-reg.html"><a href="cor-reg.html#fitting-a-line-to-data"><i class="fa fa-check"></i><b>3.1.1</b> Fitting a line to data</a></li>
<li class="chapter" data-level="3.1.2" data-path="cor-reg.html"><a href="cor-reg.html#using-linear-regression-to-predict-possum-head-lengths"><i class="fa fa-check"></i><b>3.1.2</b> Using linear regression to predict possum head lengths</a></li>
<li class="chapter" data-level="3.1.3" data-path="cor-reg.html"><a href="cor-reg.html#residuals"><i class="fa fa-check"></i><b>3.1.3</b> Residuals</a></li>
<li class="chapter" data-level="3.1.4" data-path="cor-reg.html"><a href="cor-reg.html#describing-linear-relationships-with-correlation"><i class="fa fa-check"></i><b>3.1.4</b> Describing linear relationships with correlation</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="cor-reg.html"><a href="cor-reg.html#least-squares-regression"><i class="fa fa-check"></i><b>3.2</b> Least squares regression</a><ul>
<li class="chapter" data-level="3.2.1" data-path="cor-reg.html"><a href="cor-reg.html#gift-aid-for-freshman-at-elmhurst-college"><i class="fa fa-check"></i><b>3.2.1</b> Gift aid for freshman at Elmhurst College</a></li>
<li class="chapter" data-level="3.2.2" data-path="cor-reg.html"><a href="cor-reg.html#an-objective-measure-for-finding-the-best-line"><i class="fa fa-check"></i><b>3.2.2</b> An objective measure for finding the best line</a></li>
<li class="chapter" data-level="3.2.3" data-path="cor-reg.html"><a href="cor-reg.html#finding-and-interpreting-the-least-squares-line"><i class="fa fa-check"></i><b>3.2.3</b> Finding and interpreting the least squares line</a></li>
<li class="chapter" data-level="3.2.4" data-path="cor-reg.html"><a href="cor-reg.html#extrapolation-is-treacherous"><i class="fa fa-check"></i><b>3.2.4</b> Extrapolation is treacherous</a></li>
<li class="chapter" data-level="3.2.5" data-path="cor-reg.html"><a href="cor-reg.html#describing-the-strength-of-a-fit"><i class="fa fa-check"></i><b>3.2.5</b> Describing the strength of a fit</a></li>
<li class="chapter" data-level="3.2.6" data-path="cor-reg.html"><a href="cor-reg.html#categprical-predictor-two-levels"><i class="fa fa-check"></i><b>3.2.6</b> Categorical predictors with two levels (special topic)</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="cor-reg.html"><a href="cor-reg.html#outliers-in-regression"><i class="fa fa-check"></i><b>3.3</b> Outliers in linear regression</a><ul>
<li class="chapter" data-level="3.3.1" data-path="cor-reg.html"><a href="cor-reg.html#types-of-outliers"><i class="fa fa-check"></i><b>3.3.1</b> Types of outliers</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="cor-reg.html"><a href="cor-reg.html#r-correlation-and-regression"><i class="fa fa-check"></i><b>3.4</b> <code>R</code>: Correlation and regression</a><ul>
<li class="chapter" data-level="3.4.1" data-path="cor-reg.html"><a href="cor-reg.html#intro-linear-models-r-tutorial"><i class="fa fa-check"></i><b>3.4.1</b> Interactive R tutorials</a></li>
<li class="chapter" data-level="3.4.2" data-path="intro-to-data.html"><a href="intro-to-data.html#r-labs"><i class="fa fa-check"></i><b>3.4.2</b> R labs</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="cor-reg.html"><a href="cor-reg.html#chp3-review"><i class="fa fa-check"></i><b>3.5</b> Chapter review</a><ul>
<li class="chapter" data-level="3.5.1" data-path="intro-to-data.html"><a href="intro-to-data.html#terms"><i class="fa fa-check"></i><b>3.5.1</b> Terms</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="mult-reg.html"><a href="mult-reg.html"><i class="fa fa-check"></i><b>4</b> Multivariable models</a><ul>
<li class="chapter" data-level="4.1" data-path="mult-reg.html"><a href="mult-reg.html#gapminder-world"><i class="fa fa-check"></i><b>4.1</b> Gapminder world</a></li>
<li class="chapter" data-level="4.2" data-path="mult-reg.html"><a href="mult-reg.html#simpsons-paradox-revisited"><i class="fa fa-check"></i><b>4.2</b> Simpson’s Paradox, revisited</a></li>
<li class="chapter" data-level="4.3" data-path="mult-reg.html"><a href="mult-reg.html#r-multiple-and-logistic-regression-special-topic"><i class="fa fa-check"></i><b>4.3</b> <code>R</code>: Multiple and logistic regression (special topic)</a><ul>
<li class="chapter" data-level="4.3.1" data-path="intro-to-data.html"><a href="intro-to-data.html#interactive-r-tutorials"><i class="fa fa-check"></i><b>4.3.1</b> Interactive R tutorials</a></li>
<li class="chapter" data-level="4.3.2" data-path="intro-to-data.html"><a href="intro-to-data.html#r-labs"><i class="fa fa-check"></i><b>4.3.2</b> R labs</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="inference-cat.html"><a href="inference-cat.html"><i class="fa fa-check"></i><b>5</b> Inference for categorical data</a><ul>
<li class="chapter" data-level="5.1" data-path="inference-cat.html"><a href="inference-cat.html#inf-foundations"><i class="fa fa-check"></i><b>5.1</b> Foundations of inference</a><ul>
<li class="chapter" data-level="5.1.1" data-path="inference-cat.html"><a href="inference-cat.html#Martian"><i class="fa fa-check"></i><b>5.1.1</b> Motivating example: Martian alphabet</a></li>
<li class="chapter" data-level="5.1.2" data-path="inference-cat.html"><a href="inference-cat.html#var-stat"><i class="fa fa-check"></i><b>5.1.2</b> Variability in a statistic</a></li>
<li class="chapter" data-level="5.1.3" data-path="inference-cat.html"><a href="inference-cat.html#HypothesisTesting"><i class="fa fa-check"></i><b>5.1.3</b> Hypothesis tests</a></li>
<li class="chapter" data-level="5.1.4" data-path="inference-cat.html"><a href="inference-cat.html#ConfidenceIntervals"><i class="fa fa-check"></i><b>5.1.4</b> Confidence intervals</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="inference-cat.html"><a href="inference-cat.html#normal"><i class="fa fa-check"></i><b>5.2</b> The normal distribution</a><ul>
<li class="chapter" data-level="5.2.1" data-path="inference-cat.html"><a href="inference-cat.html#normal-distribution-model"><i class="fa fa-check"></i><b>5.2.1</b> Normal distribution model</a></li>
<li class="chapter" data-level="5.2.2" data-path="inference-cat.html"><a href="inference-cat.html#standardizing-with-z-scores"><i class="fa fa-check"></i><b>5.2.2</b> Standardizing with Z-scores</a></li>
<li class="chapter" data-level="5.2.3" data-path="inference-cat.html"><a href="inference-cat.html#normal-probability-calculations-in-r"><i class="fa fa-check"></i><b>5.2.3</b> Normal probability calculations in <code>R</code></a></li>
<li class="chapter" data-level="5.2.4" data-path="inference-cat.html"><a href="inference-cat.html#normal-probability-examples"><i class="fa fa-check"></i><b>5.2.4</b> Normal probability examples</a></li>
<li class="chapter" data-level="5.2.5" data-path="inference-cat.html"><a href="inference-cat.html#rule"><i class="fa fa-check"></i><b>5.2.5</b> 68-95-99.7 rule</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="inference-cat.html"><a href="inference-cat.html#single-prop"><i class="fa fa-check"></i><b>5.3</b> One proportion</a><ul>
<li class="chapter" data-level="5.3.1" data-path="inference-cat.html"><a href="inference-cat.html#one-prop-null-boot"><i class="fa fa-check"></i><b>5.3.1</b> Simulation-based test for <span class="math inline">\(H_0: \pi = \pi_0\)</span></a></li>
<li class="chapter" data-level="5.3.2" data-path="inference-cat.html"><a href="inference-cat.html#boot-ci-prop"><i class="fa fa-check"></i><b>5.3.2</b> Bootstrap confidence interval for <span class="math inline">\(\pi\)</span></a></li>
<li class="chapter" data-level="5.3.3" data-path="inference-cat.html"><a href="inference-cat.html#theory-prop"><i class="fa fa-check"></i><b>5.3.3</b> Theory-based methods for <span class="math inline">\(\pi\)</span></a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="inference-cat.html"><a href="inference-cat.html#diff-two-prop"><i class="fa fa-check"></i><b>5.4</b> Difference of two proportions</a><ul>
<li class="chapter" data-level="5.4.1" data-path="inference-cat.html"><a href="inference-cat.html#two-prop-errors"><i class="fa fa-check"></i><b>5.4.1</b> Randomization test for <span class="math inline">\(H_0: \pi_1 - \pi_2 = 0\)</span></a></li>
<li class="chapter" data-level="5.4.2" data-path="inference-cat.html"><a href="inference-cat.html#two-prop-boot-ci"><i class="fa fa-check"></i><b>5.4.2</b> Bootstrap confidence interval for <span class="math inline">\(\pi_1 - \pi_2\)</span></a></li>
<li class="chapter" data-level="5.4.3" data-path="inference-cat.html"><a href="inference-cat.html#math-2prop"><i class="fa fa-check"></i><b>5.4.3</b> Theory-based methods for <span class="math inline">\(\pi_1 - \pi_2\)</span></a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="inference-cat.html"><a href="inference-cat.html#power"><i class="fa fa-check"></i><b>5.5</b> Power, Errors, and Practical Importance</a></li>
<li class="chapter" data-level="5.6" data-path="inference-cat.html"><a href="inference-cat.html#summary-of-z-procedures"><i class="fa fa-check"></i><b>5.6</b> Summary of Z-procedures</a></li>
<li class="chapter" data-level="5.7" data-path="inference-cat.html"><a href="inference-cat.html#r-inference-for-categorical-data"><i class="fa fa-check"></i><b>5.7</b> <code>R</code>: Inference for categorical data</a><ul>
<li class="chapter" data-level="5.7.1" data-path="intro-to-data.html"><a href="intro-to-data.html#interactive-r-tutorials"><i class="fa fa-check"></i><b>5.7.1</b> Interactive R tutorials</a></li>
<li class="chapter" data-level="5.7.2" data-path="intro-to-data.html"><a href="intro-to-data.html#r-labs"><i class="fa fa-check"></i><b>5.7.2</b> R labs</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="inference-cat.html"><a href="inference-cat.html#chp5-review"><i class="fa fa-check"></i><b>5.8</b> Chapter 5 review</a><ul>
<li class="chapter" data-level="5.8.1" data-path="intro-to-data.html"><a href="intro-to-data.html#terms"><i class="fa fa-check"></i><b>5.8.1</b> Terms</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="inference-num.html"><a href="inference-num.html"><i class="fa fa-check"></i><b>6</b> Inference for quantitative data</a><ul>
<li class="chapter" data-level="6.1" data-path="inference-num.html"><a href="inference-num.html#one-mean"><i class="fa fa-check"></i><b>6.1</b> One mean</a><ul>
<li class="chapter" data-level="6.1.1" data-path="inference-num.html"><a href="inference-num.html#bootstrap-confidence-interval-for-mu"><i class="fa fa-check"></i><b>6.1.1</b> Bootstrap confidence interval for <span class="math inline">\(\mu\)</span></a></li>
<li class="chapter" data-level="6.1.2" data-path="inference-num.html"><a href="inference-num.html#one-mean-math"><i class="fa fa-check"></i><b>6.1.2</b> Theory-based inferential methods for <span class="math inline">\(\bar{x}\)</span></a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="inference-num.html"><a href="inference-num.html#paired-data"><i class="fa fa-check"></i><b>6.2</b> Paired mean difference</a><ul>
<li class="chapter" data-level="6.2.1" data-path="inference-num.html"><a href="inference-num.html#randomization-test-for-h_0-mu_d-0"><i class="fa fa-check"></i><b>6.2.1</b> Randomization test for <span class="math inline">\(H_0: \mu_d = 0\)</span></a></li>
<li class="chapter" data-level="6.2.2" data-path="inference-num.html"><a href="inference-num.html#bootstrap-confidence-interval-for-mu_d"><i class="fa fa-check"></i><b>6.2.2</b> Bootstrap confidence interval for <span class="math inline">\(\mu_d\)</span></a></li>
<li class="chapter" data-level="6.2.3" data-path="inference-num.html"><a href="inference-num.html#mathematical-model"><i class="fa fa-check"></i><b>6.2.3</b> Mathematical model</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="inference-num.html"><a href="inference-num.html#differenceOfTwoMeans"><i class="fa fa-check"></i><b>6.3</b> Difference of two means</a><ul>
<li class="chapter" data-level="6.3.1" data-path="inference-num.html"><a href="inference-num.html#rand2mean"><i class="fa fa-check"></i><b>6.3.1</b> Randomization test for <span class="math inline">\(H_0: \mu_1 - \mu_2 = 0\)</span></a></li>
<li class="chapter" data-level="6.3.2" data-path="inference-num.html"><a href="inference-num.html#bootstrap-confidence-interval-for-mu_1---mu_2"><i class="fa fa-check"></i><b>6.3.2</b> Bootstrap confidence interval for <span class="math inline">\(\mu_1 - \mu_2\)</span></a></li>
<li class="chapter" data-level="6.3.3" data-path="inference-num.html"><a href="inference-num.html#mathematical-model-1"><i class="fa fa-check"></i><b>6.3.3</b> Mathematical model</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="inference-num.html"><a href="inference-num.html#summary-of-t-procedures"><i class="fa fa-check"></i><b>6.4</b> Summary of t-procedures</a></li>
<li class="chapter" data-level="6.5" data-path="inference-num.html"><a href="inference-num.html#r-inference-for-quantitative-data"><i class="fa fa-check"></i><b>6.5</b> <code>R</code>: Inference for quantitative data</a><ul>
<li class="chapter" data-level="6.5.1" data-path="intro-to-data.html"><a href="intro-to-data.html#interactive-r-tutorials"><i class="fa fa-check"></i><b>6.5.1</b> Interactive R tutorials</a></li>
<li class="chapter" data-level="6.5.2" data-path="intro-to-data.html"><a href="intro-to-data.html#r-labs"><i class="fa fa-check"></i><b>6.5.2</b> R labs</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="inference-num.html"><a href="inference-num.html#chp6-review"><i class="fa fa-check"></i><b>6.6</b> Chapter 6 review</a><ul>
<li class="chapter" data-level="6.6.1" data-path="intro-to-data.html"><a href="intro-to-data.html#terms"><i class="fa fa-check"></i><b>6.6.1</b> Terms</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="inference-reg.html"><a href="inference-reg.html"><i class="fa fa-check"></i><b>7</b> Inference for regression</a><ul>
<li class="chapter" data-level="7.1" data-path="inference-reg.html"><a href="inference-reg.html#r-inference-for-regression"><i class="fa fa-check"></i><b>7.1</b> <code>R</code>: Inference for regression</a><ul>
<li class="chapter" data-level="7.1.1" data-path="intro-to-data.html"><a href="intro-to-data.html#interactive-r-tutorials"><i class="fa fa-check"></i><b>7.1.1</b> Interactive R tutorials</a></li>
<li class="chapter" data-level="7.1.2" data-path="intro-to-data.html"><a href="intro-to-data.html#r-labs"><i class="fa fa-check"></i><b>7.1.2</b> R labs</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="inference-reg.html"><a href="inference-reg.html#chp7-review"><i class="fa fa-check"></i><b>7.2</b> Chapter 7 review</a><ul>
<li class="chapter" data-level="7.2.1" data-path="intro-to-data.html"><a href="intro-to-data.html#terms"><i class="fa fa-check"></i><b>7.2.1</b> Terms</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="case-studies.html"><a href="case-studies.html"><i class="fa fa-check"></i><b>8</b> Appendix: Case studies</a></li>
<li class="chapter" data-level="9" data-path="activities.html"><a href="activities.html"><i class="fa fa-check"></i><b>9</b> Appendix: Activities</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Montana State Introductory Statistics with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="inference-num" class="section level1">
<h1><span class="header-section-number">Chapter 6</span> Inference for quantitative data</h1>

<div class="chapterintro">
<p>Focusing now on statistical inference for quantitative data, again, we will revisit and expand upon the foundational aspects of hypothesis testing from Section <a href="inference-cat.html#inf-foundations">5.1</a>.</p>
<p>The important data structure for this chapter is a quantitative response variable (that is, the outcome is numerical).
The three data structures we detail are:</p>
<ul>
<li>one quantitative response variable, summarized by a single mean,</li>
<li>one quantitative response variable which is a difference across a pair of observations, summarized by a paired mean difference, and</li>
<li>a quantitative response variable broken down by a binary explanatory variable, summarized by a difference in means.</li>
</ul>
<p>When appropriate, each of the data structures will be analyzed using the two methods introduced in Section <a href="inference-cat.html#inf-foundations">5.1</a>: simulation-based and theory-based.</p>
As we build on the inferential ideas, we will visit new foundational concepts in statistical inference. One key new idea rests in estimating how the sample mean (as opposed to the sample proportion) varies from sample to sample; the resulting value is referred to as the <strong>standard error of the mean</strong>. We will also introduce a new important mathematical model, the <span class="math inline">\(t\)</span>-distribution (as the foundation for the <span class="math inline">\(t\)</span>-test).
</div>

<p>To summarize a quantitative response variable, we focus on the sample mean (instead of, for example, the sample median or the range of the observations) because of the well-studied mathematical model which describes the behavior of the sample mean.
The sample mean will be calculated in one group, two paired groups, and two independent groups. We will not cover mathematical models which describe other statistics, but the bootstrap and randomization techniques described below are immediately extendable to any function of the observed data.
The techniques described for each setting will vary slightly, but you will be well served to find the structural similarities across the different settings.</p>
<div id="one-mean" class="section level2">
<h2><span class="header-section-number">6.1</span> One mean</h2>

<div class="onebox">
<p><strong>Notation</strong>.</p>
<ul>
<li><span class="math inline">\(n\)</span> = sample size</li>
<li><span class="math inline">\(\hat{x}\)</span> = sample mean</li>
<li><span class="math inline">\(s\)</span> = sample standard deviation</li>
<li><span class="math inline">\(\mu\)</span> = population mean</li>
<li><span class="math inline">\(\sigma\)</span> = population standard deviation
</div></li>
</ul>
<p>In this section, we explore the situation where we focus on a single mean of a quantitative variable, and we introduce a new simulation method, <strong>bootstrapping</strong>.
Bootstrapping is best suited for modeling studies where the data have been generated through random sampling from a population.</p>
<p>If the goal is to produce a range of possible values for a population value, then in an ideal world, we would sample data from the population again and recompute the sample mean.<br />
Then we could do it again.
And again.
And so on until we have a good sense of the variability of our original estimate.
The ideal world where sampling data is free or extremely cheap is almost never the case, and taking repeated samples from a population is usually impossible.
So, instead of using a “resample from the population” approach, bootstrapping uses a “resample from the sample” approach.</p>
<p>Sometime the mathematical theory for how an estimate varies is well-known; this is the case for the sample proportion as seen in Section <a href="inference-cat.html#theory-prop">5.3.3</a> and the sample mean seen later in this Chapter.
However, some statistics don’t have simple theory for how they vary, and bootstrapping provides a computational approach for providing interval estimates for almost any population parameter.</p>
<div id="bootstrap-confidence-interval-for-mu" class="section level3">
<h3><span class="header-section-number">6.1.1</span> Bootstrap confidence interval for <span class="math inline">\(\mu\)</span></h3>
<p>As an employer who subsidizes housing for your employees, you need to know the average month rental price for a three bedroom flat in Edinburgh.
In order to walk through the example more clearly, let’s say that you are only able to randomly sample five Edinburgh flats (if this were a real example, you would surely be able to take a much larger sample size, possibly even being able to measure the entire population!).</p>
<p>Figure <a href="inference-num.html#fig:5flats">6.1</a> presents the details of the random sample of observations where the monthly rent of five flats has been recorded.</p>
<div class="figure" style="text-align: center"><span id="fig:5flats"></span>
<img src="06/figures/5flats.png" alt="5 flats" width="75%" />
<p class="caption">
Figure 6.1: 5 flats
</p>
</div>
<p>The sample average monthly rent of £ 1648 is a first guess at the price of three bedroom flats. However, as a student of statistics, you understand that one sample mean based on a sample of five observations will not necessarily equal the true population average rent for all three bedroom flats in Edinburgh.
Indeed, you can see that the observed rent prices vary with a standard deviation of £ 340.232, and surely the average monthly rent would be different if a different sample of size five had been taken from the population.
Fortunately, we can use bootstrapping to approximate the variability of the sample mean from sample to sample.</p>

<div class="todo">
Revise below to remove duplication from bootstrap CI for one proportion section.
</div>

<div id="variability-of-the-statistic" class="section level4 unnumbered">
<h4>Variability of the statistic</h4>
<p>As with the inferential ideas covered in Chapter <a href="inference-cat.html#inference-cat">5</a>, the inferential analysis methods in this chapter are grounded in quantifying how one data set differs from another when they are both taken from the same population.
It doesn’t make sense to take repeated samples from the same population because if you have the means to take more samples, a larger sample size will benefit you more than the exact same sample twice. Instead, with bootstrapping, we measure how the samples behave under an estimate of the population—the sample.
By taking repeated samples from the estimated population, the variability from sample to sample can be observed.</p>
<p>Figure <a href="inference-num.html#fig:bootstrapping">6.2</a> shows how the unknown original population can be estimated by using many duplicates of the sample. This estimated population—consisting of infinitely many copies of the original sample—can then be used to generate bootstrapped resamples.</p>
<div class="figure" style="text-align: center"><span id="fig:bootstrapping"></span>
<img src="06/figures/bootstrapping.png" alt="Using the original sample of five Edinburgh flats to generate an estimated population, which is then used to generate bootstrapped resamples. This process of generating a bootstrapped sample is equivalent to sampling five flats from the original sample, with replacement." width="75%" />
<p class="caption">
Figure 6.2: Using the original sample of five Edinburgh flats to generate an estimated population, which is then used to generate bootstrapped resamples. This process of generating a bootstrapped sample is equivalent to sampling five flats from the original sample, with replacement.
</p>
</div>
<p>It turns out that in practice, it is very difficult for computers to work with an infinite population (with the same proportional breakdown as in the sample).
However, there is a physical and computational model which produces an equivalent bootstrap distribution of the sample mean in a computationally efficient manner.
Consider the observed data to be a bag of five marbles. Each marble corresponds to one flat, and is labeled by the rent price. By drawing the marbles out of the bag <em>with replacement</em> (after we draw one, we put it back before drawing another), we depict the same sampling <strong>process</strong> as was done with the infinitely large estimated population.
Note in Figure <a href="inference-num.html#fig:bootstrapping">6.2</a> that when sampling the original observations, a particular data point may end up in the new sample one time, several times, or not at all.</p>
<p>In Figure <a href="inference-num.html#fig:bootstrapping">6.2</a>, the repeated bootstrap resamples are obviously different both from each other and from the original sample.
Since the bootstrap resamples are taken from the same (estimated) population, these differences are due entirely to natural variability in the sampling procedure.
By summarizing each of the bootstrap resamples (here, using the sample mean), we see, directly, the variability of the sample mean, <span class="math inline">\(\bar{x}\)</span>, from sample to sample.
The distribution of <span class="math inline">\(\hat{x}_{boot}\)</span> for the Edinburgh flats is shown in Figure <a href="inference-num.html#fig:flatsbsmean">6.3</a>.</p>
<div class="figure" style="text-align: center"><span id="fig:flatsbsmean"></span>
<img src="06-inference-num_files/figure-html/flatsbsmean-1.png" alt="Distribution of bootstrapped means from 1,000 simulated bootstrapped samples generated by sampling with replacement from our original sample of five Edinburgh flats. The histogram provides a sense for the variability of the average rent values from sample to sample for samples of size 5." width="70%" />
<p class="caption">
Figure 6.3: Distribution of bootstrapped means from 1,000 simulated bootstrapped samples generated by sampling with replacement from our original sample of five Edinburgh flats. The histogram provides a sense for the variability of the average rent values from sample to sample for samples of size 5.
</p>
</div>
<p>The bootstrapped average rent prices vary from £ 1250 to £ 1995 (with a small observed sample of size 5, a bootstrap resample can sometimes, although rarely, include only repeated measurements of the same observation).</p>

<div class="onebox">
<p><strong>Bootstrapping</strong>.</p>
<ol style="list-style-type: decimal">
<li>Take a random sample of size <span class="math inline">\(n\)</span> from the original sample, <em>with replacement</em>. This is called a <strong>bootstrapped resample</strong>.</li>
<li>Record the sample mean (or statistic of interest) from the boostrapped resample. This is called a <strong>bootstrapped statistic</strong>.</li>
<li>Repeat steps (1) and (2) 1000s of times.</li>
</ol>
<p>Use the standard deviation of the distribution of bootstrapped statistics as your estimate for the standard deviation of the sampling distribution of sample means—the amount we would expect a sample mean to typically deviate from the population mean.</p>
Since this bootstrapped standard deviation of statistics is an <em>estimate</em> of the standard deviation of sample means—and not the actual value, which is unknown—we call this a <strong>standard error</strong> of the sample mean.
</div>

<p>Due to theory that is beyond this text, we know that the bootstrap means <span class="math inline">\(\bar{x}_{boot}\)</span> vary around the original sample mean, <span class="math inline">\(\bar{x}\)</span>, in a similar way to how different sample (i.e., different data sets which would produce different <span class="math inline">\(\bar{x}\)</span> values) means vary around the true parameter <span class="math inline">\(\mu\)</span>.
Therefore, an interval estimate for <span class="math inline">\(\mu\)</span> can be produced using the <span class="math inline">\(\bar{x}_{boot}\)</span> values themselves.The <strong>bootstrap confidence interval</strong> for <span class="math inline">\(\mu\)</span>, the population mean rent price for three bedroom flats in Edinburgh, is found by locating the middle 95% (for a 95% confidence interval) of the bootstrapped sample means in Figure @ref{fig:flatsbsmean}.</p>

<div class="onebox">
<p><strong>95% Bootstrap confidence interval for a population mean <span class="math inline">\(\mu\)</span>.</strong></p>
The 95% bootstrap confidence interval for the parameter <span class="math inline">\(\mu\)</span> can be obtained directly using the ordered values <span class="math inline">\(\bar{x}_{boot}\)</span> values. Consider the sorted <span class="math inline">\(\bar{x}_{boot}\)</span> values, and let <span class="math inline">\(\bar{x}_{boot, 0.025}\)</span> be the 2.5% value and <span class="math inline">\(\bar{x}_{boot, 0.025}\)</span> be the 97.5% value. The 95% confidence interval is given by:
<center>
(<span class="math inline">\(\hat{p}_{bs, 0.025}\)</span>, <span class="math inline">\(\hat{p}_{bs, 0.975}\)</span>)
</center>
</div>

<p>You can find confidence intervals of difference confidence levels by changing the percent of the distribution you take, e.g., locate the middle 90% of the bootstrapped statistics for a 90% confidence interval.</p>

<div class="guidedpractice">
To find the middle 95% of a distribution, which two percentiles would form its boundaries?<a href="#fn129" class="footnote-ref" id="fnref129"><sup>129</sup></a>
</div>


<div class="example">
<p>Using Figure <a href="inference-num.html#fig:flatsbsmean">6.3</a>, find the 90% and 95% confidence intervals for the true mean monthly rental price of a three bedroom flat in Edinburgh.</p>
<hr />
<p>A 90% confidence interval is given by £ 1429 to £ 1876. The conclusion is that we are 90% confident that the true average rental price for three bedroom flats in Edinburgh lies somewhere between £ 1429 and £ 1876.</p>
A 95% confidence interval is given by £ 1389.75 to £ 1916. The conclusion is that we are 90% confident that the true average rental price for three bedroom flats in Edinburgh lies somewhere between £ 1389.75 and £ 1916.
</div>

</div>
<div id="bootstrap-percentile-confidence-interval-for-sigma" class="section level4 unnumbered">
<h4>Bootstrap percentile confidence interval for <span class="math inline">\(\sigma\)</span></h4>
<p>Suppose that the research question at hand seeks to understand how variable the rental price of the flats are in Edinburgh.
That is, your interest is no longer in the average rental price of the flats but in the <em>standard deviation</em> of the rental prices of all three bedroom flats in Edinburgh, <span class="math inline">\(\sigma\)</span>.
You may have already realized that the sample standard deviation, <span class="math inline">\(s\)</span>, will work as a good <strong>point estimate</strong> for the parameter of interest: the population standard deviation, <span class="math inline">\(\sigma\)</span>.
The point estimate of the five observations is calculated to be <span class="math inline">\(s =\)</span> £ 340.23.
While <span class="math inline">\(s =\)</span> £ 340.23 might be a good guess for <span class="math inline">\(\sigma\)</span>, we prefer to have an interval
Although there is a mathematical model which describes how <span class="math inline">\(s\)</span> varies from sample to sample, the mathematical model will not be presented in this text.
But even without the mathematical model, bootstrapping can be used to find a confidence interval for the parameter <span class="math inline">\(\sigma\)</span>.</p>

<div class="example">
<p>Describe the bootstrap distribution for the standard deviation shown in Figure <a href="inference-num.html#fig:flatsbssd">6.4</a>.</p>
<hr />
The distribution is skewed left and centered near £ 340.23, which is the point estimate from the original data. Most observations in this distribution lie between £ 0 and £ 408.1.
</div>


<div class="guidedpractice">
<p>Using Figure <a href="inference-num.html#fig:flatsbssd">6.4</a>, find <em>and interpret</em> a 90% confidence interval for the population standard deviation for three bedroom flat prices in Edinburgh.^[By looking at the percentile values in Figure <a href="inference-num.html#fig:flatsbssd">6.4</a>, the middle 90% of the bootstrap standard deviations are given by the 5 percentile (£ 153.9) and 95 percentile (£ 385.6). That is, we are 90% confident that the true standard deviation of rent prices is between £ 153.9 and £ 385.6.</p>
Note, the problem was set up as 90% to indicate that there was not a need for a high level of confidence (such a 95% or 99%). A lower degree of confidence increases potential for error, but it also produces a more narrow interval. ]
</div>

<div class="figure" style="text-align: center"><span id="fig:flatsbssd"></span>
<img src="06-inference-num_files/figure-html/flatsbssd-1.png" alt="The original Edinburgh data is bootstrapped 1,000 times. The histogram provides a sense for the variability of the standard deviation of the rent values from sample to sample." width="70%" />
<p class="caption">
Figure 6.4: The original Edinburgh data is bootstrapped 1,000 times. The histogram provides a sense for the variability of the standard deviation of the rent values from sample to sample.
</p>
</div>
</div>
<div id="bootstrapping-is-not-a-solution-to-small-sample-sizes" class="section level4 unnumbered">
<h4>Bootstrapping is not a solution to small sample sizes!</h4>
<p>The example presented above is done for a sample with only five observations.
As with analysis techniques that build on mathematical models, bootstrapping works best when a large random sample has been taken from the population.
Bootstrapping is a method for capturing the variability of a statistic when the mathematical model is unknown (it is not a method for navigating small samples).
As you might guess, the larger the random sample, the more accurately that sample will represent the target population.</p>
</div>
</div>
<div id="one-mean-math" class="section level3">
<h3><span class="header-section-number">6.1.2</span> Theory-based inferential methods for <span class="math inline">\(\bar{x}\)</span></h3>
<p>As with the sample proportion, the variability of the sample mean is well described by the mathematical theory given by the Central Limit Theorem. Similar to how we can model the behavior of the sample proportion <span class="math inline">\(\hat{p}\)</span> using a normal distribution, the sample mean <span class="math inline">\(\bar{x}\)</span> can also be modeled using
a normal distribution when certain conditions are met.
However, because of missing information about the inherent variability in the population, a <span class="math inline">\(t\)</span>-distribution is used in place of the standard normal when performing hypothesis test or confidence interval analyses.</p>
<p>The sample mean tends to follow
a normal distribution centered at the population mean, <span class="math inline">\(\mu\)</span>,
when certain conditions are met.
Additionally, we can compute a standard error for the sample
mean using the population standard deviation <span class="math inline">\(\sigma\)</span>
and the sample size <span class="math inline">\(n\)</span>.</p>

<div class="onebox">
<strong>Central Limit Theorem for the sample mean</strong><br />
When we collect a sufficiently large sample of
<span class="math inline">\(n\)</span> independent observations from a population with
mean <span class="math inline">\(\mu\)</span> and standard deviation <span class="math inline">\(\sigma\)</span>,
the sampling distribution of <span class="math inline">\(\bar{x}\)</span> will be nearly
normal with
<span class="math display">\[\begin{align*}
  &amp;\text{Mean}=\mu
  &amp;&amp;\text{Standard Error }(SE) = \frac{\sigma}{\sqrt{n}}
  \end{align*}\]</span>
</div>

<p>Before diving into confidence intervals and hypothesis
tests using <span class="math inline">\(\bar{x}\)</span>, we first need to cover two topics:</p>
<ul>
<li>When we modeled <span class="math inline">\(\hat{p}\)</span> using the normal distribution,
certain conditions had to be satisfied.
The conditions for working with <span class="math inline">\(\bar{x}\)</span>
are a little more complex, and below, we will discuss
how to check conditions for inference using a mathematical model.</li>
<li>The standard error is dependent on the population
standard deviation, <span class="math inline">\(\sigma\)</span>.
However, we rarely know <span class="math inline">\(\sigma\)</span>, and instead
we must estimate it.
Because this estimation is itself imperfect,
we use a new distribution called the
<strong><span class="math inline">\(t\)</span>-distribution</strong>
to fix this problem, which we discuss in</li>
</ul>
<div id="evaluating-the-two-conditions-required-for-modeling-barx" class="section level4 unnumbered">
<h4>Evaluating the two conditions required for modeling <span class="math inline">\(\bar{x}\)</span></h4>
<p>Two conditions are required to apply the
Central Limit Theorem
for a sample mean <span class="math inline">\(\bar{x}\)</span>:</p>
<ul>
<li><p><strong>Independence.</strong> The sample observations must be independent,
The most common way to satisfy this condition is
when the sample is a simple random sample from the
population.
If the data come from a random process,
analogous to rolling a die,
this would also satisfy the independence condition.</p></li>
<li><p><strong>Normality.</strong> When a sample is small,
we also require that the sample observations
come from a normally distributed population.
We can relax this condition more and more
for larger and larger sample sizes.
This condition is obviously vague,
making it difficult to evaluate,
so next we introduce a couple rules of thumb
to make checking this condition easier.</p></li>
</ul>

<div class="onebox">
<p><strong>General rule: how to perform the normality check</strong></p>
<p>There is no perfect way to check the normality condition,
so instead we use two general rules:</p>
<ul>
<li><span class="math inline">\(\mathbf{n &lt; 30}\)</span>: If the sample size <span class="math inline">\(n\)</span> is less than 30
and there are no clear outliers in the data,
then we typically assume the data come from
a nearly normal distribution to satisfy the
condition.<br />
</li>
<li><span class="math inline">\(\mathbf{n \geq 30}\)</span>: If the sample size <span class="math inline">\(n\)</span> is at least 30
and there are no <em>particularly extreme</em> outliers,
then we typically assume the sampling distribution
of <span class="math inline">\(\bar{x}\)</span> is nearly normal, even if the underlying
distribution of individual observations is not.
</div></li>
</ul>
<p>In this first course in statistics, you aren’t expected
to develop perfect judgement on the normality condition.
However, you are expected to be able to handle
clear cut cases based on the rules of thumb.<a href="#fn130" class="footnote-ref" id="fnref130"><sup>130</sup></a></p>

<div class="example">
<p>Consider the following two plots
that come from simple random samples from
different populations.
Their sample sizes are <span class="math inline">\(n_1 = 15\)</span> and <span class="math inline">\(n_2 = 50\)</span>.</p>
<p>Are the independence and normality conditions met
in each case?</p>
<hr />
<p>Each samples is from a simple random sample of its
respective population, so the independence condition
is satisfied.
Let’s next check the normality condition for
each using the rule of thumb.</p>
<p>The first sample has fewer than 30 observations,
so we are watching for any clear outliers.
None are present; while there is a small gap in the
histogram on the right, this gap is small and
20% of the observations in this small sample
are represented in that far right bar of the histogram,
so we can hardly call these clear outliers.
With no clear outliers, the normality condition
is reasonably met.</p>
The second sample has a sample size greater than 30 and
includes an outlier that appears to be roughly 5 times
further from the center of the distribution than the
next furthest observation.
This is an example of a particularly extreme outlier,
so the normality condition would not be satisfied.
</div>

<p><img src="06-inference-num_files/figure-html/outliersandsscondition-1.png" width="70%" style="display: block; margin: auto;" /><img src="06-inference-num_files/figure-html/outliersandsscondition-2.png" width="70%" style="display: block; margin: auto;" /></p>
<p>In practice, it’s typical to also do a mental check to evaluate
whether we have reason to believe the underlying population
would have moderate skew (if <span class="math inline">\(n &lt; 30\)</span>)
or have particularly extreme outliers <span class="math inline">\((n \geq 30)\)</span>
beyond what we observe in the data.
For example, consider the number of followers
for each individual account on Twitter,
and then imagine this distribution.
The large majority of accounts have built up
a couple thousand followers or fewer,
while a relatively tiny fraction have amassed
tens of millions of followers,
meaning the distribution is extremely skewed.
When we know the data come from such an extremely
skewed distribution,
it takes some effort to understand what sample
size is large enough for the normality condition
to be satisfied.</p>
<p></p>
</div>
<div id="introducing-the-t-distribution" class="section level4 unnumbered">
<h4>Introducing the <span class="math inline">\(t\)</span>-distribution</h4>
<p>
</p>
<p>In practice, we cannot directly calculate the standard error
for <span class="math inline">\(\bar{x}\)</span> since we do not know the population standard
deviation, <span class="math inline">\(\sigma\)</span>.
We encountered a similar issue when computing the standard
error for a sample proportion, which relied on the population
proportion, <span class="math inline">\(p\)</span>.
Our solution in the proportion context was to use sample
value in place
of the population value when computing the standard error.
We’ll employ a similar strategy for computing the standard
error of <span class="math inline">\(\bar{x}\)</span>, using the sample
standard deviation <span class="math inline">\(s\)</span> in place of <span class="math inline">\(\sigma\)</span>:
<span class="math display">\[\begin{align*}
SE = \frac{\sigma}{\sqrt{n}} \approx \frac{s}{\sqrt{n}}
\end{align*}\]</span>
This strategy tends to work well when we have
a lot of data and can estimate <span class="math inline">\(\sigma\)</span> using <span class="math inline">\(s\)</span> accurately.
However, the estimate is less precise with smaller samples,
and this leads to problems when using the normal
distribution to model <span class="math inline">\(\bar{x}\)</span>.</p>
<p>We’ll find it useful to use a new distribution for
inference calculations called the <strong><span class="math inline">\(t\)</span>-distribution</strong>.
A <span class="math inline">\(t\)</span>-distribution, shown as a solid line in
Figure <a href="inference-num.html#fig:tDistCompareToNormalDist">6.5</a>, has a bell shape.
However, its tails are thicker than the normal distribution’s,
meaning observations are more likely to fall beyond two
standard deviations from the mean than under the normal
distribution.</p>
<p>The extra thick tails of the <span class="math inline">\(t\)</span>-distribution are exactly
the correction needed to resolve the problem of using <span class="math inline">\(s\)</span>
in place of <span class="math inline">\(\sigma\)</span> in the <span class="math inline">\(SE\)</span> calculation.</p>
<div class="figure" style="text-align: center"><span id="fig:tDistCompareToNormalDist"></span>
<img src="06-inference-num_files/figure-html/tDistCompareToNormalDist-1.png" alt="Comparison of a $t$-distribution and a normal distribution." width="70%" />
<p class="caption">
Figure 6.5: Comparison of a <span class="math inline">\(t\)</span>-distribution and a normal distribution.
</p>
</div>
<p>The <span class="math inline">\(t\)</span>-distribution is always centered at zero and
has a single parameter: degrees of freedom.
The <strong>degrees of freedom</strong> 
{degrees of freedom (<span class="math inline">\(df\)</span>)!<span class="math inline">\(t\)</span>-distribution}
describes the precise form of the bell-shaped <span class="math inline">\(t\)</span>-distribution.
Several <span class="math inline">\(t\)</span>-distributions are shown in
Figure <a href="inference-num.html#fig:tDistConvergeToNormalDist">6.6</a>
in comparison to the normal distribution.</p>
<p>In general, we’ll use a <span class="math inline">\(t\)</span>-distribution
with <span class="math inline">\(df = n - 1\)</span> to model the sample mean
when the sample size is <span class="math inline">\(n\)</span>.
That is, when we have more observations,
the degrees of freedom will be larger and
the <span class="math inline">\(t\)</span>-distribution will look more like the
standard normal distribution;
when the degrees of freedom is about 30 or more,
the <span class="math inline">\(t\)</span>-distribution is nearly indistinguishable
from the normal distribution.</p>
<div class="figure" style="text-align: center"><span id="fig:tDistConvergeToNormalDist"></span>
<img src="06-inference-num_files/figure-html/tDistConvergeToNormalDist-1.png" alt="The larger the degrees of freedom, the more closely the $t$-distribution resembles the standard normal distribution." width="70%" />
<p class="caption">
Figure 6.6: The larger the degrees of freedom, the more closely the <span class="math inline">\(t\)</span>-distribution resembles the standard normal distribution.
</p>
</div>

<div class="onebox">
<p><strong>Degrees of freedom: df</strong></p>
<p>The degrees of freedom describes the shape of the
<span class="math inline">\(t\)</span>-distribution.
The larger the degrees of freedom, the more closely
the distribution approximates the normal model.</p>
When modeling <span class="math inline">\(\bar{x}\)</span> using the <span class="math inline">\(t\)</span>-distribution,
use <span class="math inline">\(df = n - 1\)</span>.
</div>

<p>The <span class="math inline">\(t\)</span>-distribution allows us greater flexibility than
the normal distribution when analyzing numerical data.
In practice, it’s common to use statistical software,
such as R, Python, or SAS for these analyses.
In R, the function used for calculating probabilities under a <span class="math inline">\(t\)</span>-distribution is <code>pt()</code> (which should seem similar to previous R functions, <code>pnorm()</code> and <code>pchisq()</code>).
Don’t forget that with the <span class="math inline">\(t\)</span>-distribution, the degrees of freedom must always be specified!</p>
<!--
Alternatively, a graphing calculator or a
\termsub{$\pmb{t}$-table}{t-table@$t$-table} may be used;
the $t$-table is similar to the normal distribution table,
and it may be found in Appendix \ref{tDistributionTable},
which includes usage instructions and examples
for those who wish to use this option.
-->
<p>No matter the approach you choose, apply your method
using the examples below to confirm your working
understanding of the <span class="math inline">\(t\)</span>-distribution.</p>

<div class="example">
<p>What proportion of the <span class="math inline">\(t\)</span>-distribution
with 18 degrees of freedom falls below -2.10?</p>
<hr />
<p>Just like a normal probability problem, we first draw
the picture in Figure <a href="inference-num.html#fig:tDistDF18LeftTail2Point10">6.7</a>
and shade the area below -2.10.</p>
Using statistical software, we can obtain a precise
value: 0.0250.
</div>

<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="inference-num.html#cb21-1"></a><span class="co"># using pt() to find probability under the $t$-distribution</span></span>
<span id="cb21-2"><a href="inference-num.html#cb21-2"></a><span class="kw">pt</span>(<span class="op">-</span><span class="fl">2.10</span>, <span class="dt">df =</span> <span class="dv">18</span>)</span>
<span id="cb21-3"><a href="inference-num.html#cb21-3"></a><span class="co">#&gt; [1] 0.025</span></span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:tDistDF18LeftTail2Point10"></span>
<img src="06-inference-num_files/figure-html/tDistDF18LeftTail2Point10-1.png" alt="The $t$-distribution with 18 degrees of freedom. The area below -2.10 has been shaded." width="70%" />
<p class="caption">
Figure 6.7: The <span class="math inline">\(t\)</span>-distribution with 18 degrees of freedom. The area below -2.10 has been shaded.
</p>
</div>

<div class="example">
<p>A <span class="math inline">\(t\)</span>-distribution with 20 degrees of freedom
is shown in the top panel of
Figure <a href="inference-num.html#fig:tDistDF20RightTail1Point65">6.8</a>.
Estimate the proportion of the distribution falling
above 1.65.</p>
<hr />
With a normal distribution, this would correspond to
about 0.05, so we should expect the <span class="math inline">\(t\)</span>-distribution
to give us a value in this neighborhood.
Using statistical software: 0.0573.
</div>

<div class="figure" style="text-align: center"><span id="fig:tDistDF20RightTail1Point65"></span>
<img src="06-inference-num_files/figure-html/tDistDF20RightTail1Point65-1.png" alt="Top: The $t$-distribution with 20 degrees of freedom, with the area above 1.65 shaded. Bottom: The $t$-distribution with 2 degrees of freedom, with the area further than 3 units from 0 shaded." width="70%" /><img src="06-inference-num_files/figure-html/tDistDF20RightTail1Point65-2.png" alt="Top: The $t$-distribution with 20 degrees of freedom, with the area above 1.65 shaded. Bottom: The $t$-distribution with 2 degrees of freedom, with the area further than 3 units from 0 shaded." width="70%" />
<p class="caption">
Figure 6.8: Top: The <span class="math inline">\(t\)</span>-distribution with 20 degrees of freedom, with the area above 1.65 shaded. Bottom: The <span class="math inline">\(t\)</span>-distribution with 2 degrees of freedom, with the area further than 3 units from 0 shaded.
</p>
</div>

<div class="example">
<p>A <span class="math inline">\(t\)</span>-distribution with 2 degrees of freedom
is shown in the bottom panel of
Figure <a href="inference-num.html#fig:tDistDF20RightTail1Point65">6.8</a>.
Estimate the proportion of the distribution falling more
than 3 units from the mean (above or below).</p>
<hr />
With so few degrees of freedom, the <span class="math inline">\(t\)</span>-distribution will
give a more notably different value than the normal
distribution.
Under a normal distribution, the area would be about
0.003 using the 68-95-99.7 rule.
For a <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(df = 2\)</span>, the area in both
tails beyond 3 units totals 0.0955.
This area is dramatically different than what
we obtain from the normal distribution.
</div>


<div class="guidedpractice">
What proportion of the <span class="math inline">\(t\)</span>-distribution with 19 degrees
of freedom falls above -1.79 units?
Use your preferred method for finding tail areas.<a href="#fn131" class="footnote-ref" id="fnref131"><sup>131</sup></a>
</div>

<p>
</p>
</div>
<div id="one-sample-t-confidence-intervals" class="section level4 unnumbered">
<h4>One sample <span class="math inline">\(t\)</span>-confidence intervals</h4>
<p></p>
<p>Let’s get our first taste of applying the <span class="math inline">\(t\)</span>-distribution
in the context of an example about the mercury content
of dolphin muscle.
Elevated mercury concentrations are an important problem
for both dolphins
and other animals, like humans, who occasionally eat them.</p>
<div class="figure" style="text-align: center"><span id="fig:rissosDolphin"></span>
<img src="06/figures/rissosDolphin.jpg" alt="A Risso's dolphin. Photo by Mike Baird, www.bairdphotos.com" width="75%" />
<p class="caption">
Figure 6.9: A Risso’s dolphin. Photo by Mike Baird, www.bairdphotos.com
</p>
</div>
</div>
<div id="observed-data" class="section level4 unnumbered">
<h4>Observed data</h4>
<p>We will identify a confidence interval for the average mercury content in dolphin muscle using a sample of 19 Risso’s dolphins from the Taiji area in Japan. The data are summarized in Table <a href="inference-num.html#tab:summaryStatsOfHgInMuscleOfRissosDolphins">6.1</a>. The minimum and maximum observed values can be used to evaluate whether or not there are clear outliers.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:summaryStatsOfHgInMuscleOfRissosDolphins">Table 6.1: </span>Summary of mercury content in the muscle of 19 Risso’s dolphins from the Taiji area. Measurements are in micrograms of mercury per wet gram
of muscle (<span class="math inline">\(\mu\)</span>g/wet g).
</caption>
<thead>
<tr>
<th style="text-align:right;">
<span class="math inline">\(n\)</span>
</th>
<th style="text-align:right;">
<span class="math inline">\(\bar{x}\)</span>
</th>
<th style="text-align:right;">
s
</th>
<th style="text-align:right;">
minimum
</th>
<th style="text-align:right;">
maximum
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
19
</td>
<td style="text-align:right;">
4.4
</td>
<td style="text-align:right;">
2.3
</td>
<td style="text-align:right;">
1.7
</td>
<td style="text-align:right;">
9.2
</td>
</tr>
</tbody>
</table>

<div class="example">
<p>Are the independence and
normality conditions satisfied for this data set?</p>
<hr />
The observations are a simple random sample,
therefore independence is reasonable.
The summary statistics in
Table <a href="inference-num.html#tab:summaryStatsOfHgInMuscleOfRissosDolphins">6.1</a>
do not suggest any clear outliers, with
all observations are within 2.5 standard deviations
of the mean.
Based on this evidence, the normality condition
seems reasonable.
</div>

<p>In the normal model, we used <span class="math inline">\(z^{\star}\)</span> and the standard error to determine the width of a confidence interval. We revise the confidence interval formula slightly when using the <span class="math inline">\(t\)</span>-distribution:
<span class="math display">\[\begin{align*}
&amp;\text{point estimate} \ \pm\  t^{\star}_{df} \times SE
&amp;&amp;\to
&amp;&amp;\bar{x} \ \pm\  t^{\star}_{df} \times \frac{s}{\sqrt{n}}
\end{align*}\]</span></p>

<div class="example">
<p>Using the summary statistics in
Table <a href="inference-num.html#tab:summaryStatsOfHgInMuscleOfRissosDolphins">6.1</a>,
compute the standard error for the average
mercury content in the <span class="math inline">\(n = 19\)</span> dolphins.</p>
<hr />
We plug in <span class="math inline">\(s\)</span> and <span class="math inline">\(n\)</span> into the formula:
<span class="math inline">\(SE  = s / \sqrt{n}  = 2.3 / \sqrt{19}  = 0.528\)</span>.
</div>

<p>The value <span class="math inline">\(t^{\star}_{df}\)</span> is a cutoff we obtain based on the
confidence level and the <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(df\)</span> degrees
of freedom.
That cutoff is found in the same way as with a normal
distribution: we find <span class="math inline">\(t^{\star}_{df}\)</span> such that
the fraction of the <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(df\)</span> degrees
of freedom within a distance <span class="math inline">\(t^{\star}_{df}\)</span>
of 0 matches the confidence level of interest.</p>

<div class="example">
<p>When <span class="math inline">\(n = 19\)</span>, what is the appropriate
degrees of freedom?
Find <span class="math inline">\(t^{\star}_{df}\)</span> for this degrees of freedom
and the confidence level of 95%</p>
<hr />
<p>The degrees of freedom is easy to calculate:
<span class="math inline">\(df = n - 1 = 18\)</span>.</p>
Using statistical software, we find the cutoff where
the upper tail is equal to 2.5%:
<span class="math inline">\(t^{\star}_{18} = 2.10\)</span>.
The area below -2.10 will also be equal to 2.5%.
That is, 95% of the <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(df = 18\)</span>
lies within 2.10 units of 0.
</div>

<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="inference-num.html#cb22-1"></a><span class="co"># use qt() to find the t-cutoff (with 95% in the middle)</span></span>
<span id="cb22-2"><a href="inference-num.html#cb22-2"></a><span class="kw">qt</span>(<span class="fl">0.025</span>, <span class="dt">df =</span> <span class="dv">18</span>)</span>
<span id="cb22-3"><a href="inference-num.html#cb22-3"></a><span class="co">#&gt; [1] -2.1</span></span>
<span id="cb22-4"><a href="inference-num.html#cb22-4"></a><span class="kw">qt</span>(<span class="fl">0.975</span>, <span class="dt">df =</span> <span class="dv">18</span>)</span>
<span id="cb22-5"><a href="inference-num.html#cb22-5"></a><span class="co">#&gt; [1] 2.1</span></span></code></pre></div>

<div class="onebox">
<p><strong>Degrees of freedom for a single sample.</strong></p>
If the sample has <span class="math inline">\(n\)</span> observations and we are examining a single mean, then we use the <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(df=n-1\)</span> degrees of freedom.
</div>


<div class="example">
<p>Compute and interpret the 95% confidence interval
for the average mercury content in Risso’s dolphins.</p>
<hr />
We can construct the confidence interval as
<span class="math display">\[\begin{align*}
  \bar{x} \ \pm\  t^{\star}_{18} \times SE
    \quad \to \quad 4.4 \ \pm\  2.10 \times 0.528
    \quad \to \quad (3.29, 5.51)
  \end{align*}\]</span>
We are 95% confident the average mercury content of muscles
in Risso’s dolphins is between 3.29 and 5.51 <span class="math inline">\(\mu\)</span>g/wet gram,
which is considered extremely high.
</div>

<p></p>

<div class="onebox">
<p><strong>Finding a <span class="math inline">\(t\)</span>-confidence interval for the mean, <span class="math inline">\(\mu\)</span>.</strong></p>
Based on a sample of <span class="math inline">\(n\)</span> independent and nearly normal
observations, a confidence interval for the population
mean is
<span class="math display">\[\begin{align*}
  &amp;\text{point estimate} \ \pm\  t^{\star}_{df} \times SE
  &amp;&amp;\to
  &amp;&amp;\bar{x} \ \pm\  t^{\star}_{df} \times \frac{s}{\sqrt{n}}
  \end{align*}\]</span>
where <span class="math inline">\(\bar{x}\)</span> is the sample mean, <span class="math inline">\(t^{\star}_{df}\)</span>
corresponds to the confidence level and degrees of freedom
<span class="math inline">\(df\)</span>, and <span class="math inline">\(SE\)</span> is the standard error as estimated by
the sample.
</div>


<div class="guidedpractice">
The FDA’s webpage provides some data on mercury content of fish.
Based on a sample of 15 croaker white fish (Pacific),
a sample mean and standard deviation were computed as 0.287
and 0.069 ppm (parts per million), respectively.
The 15 observations ranged from 0.18 to 0.41 ppm.
We will assume these observations are independent.
Based on the summary statistics of the data,
do you have any objections to the normality condition
of the individual observations?<a href="#fn132" class="footnote-ref" id="fnref132"><sup>132</sup></a>
</div>

<p></p>

<div class="example">
<p>Estimate the standard error of
<span class="math inline">\(\bar{x} = 0.287\)</span> ppm using the data summaries in the previous Guided Practice. If we are to use the <span class="math inline">\(t\)</span>-distribution to create a
90% confidence interval for the actual mean of the
mercury content, identify the degrees of freedom
and <span class="math inline">\(t^{\star}_{df}\)</span>.</p>
<hr />
<p>The standard error: <span class="math inline">\(SE = \frac{0.069}{\sqrt{15}} = 0.0178\)</span>.</p>
<p>Degrees of freedom: <span class="math inline">\(df = n - 1 = 14\)</span>.</p>
Since the goal is a 90% confidence interval,
we choose <span class="math inline">\(t_{14}^{\star}\)</span> so that the two-tail area
is 0.1:
<span class="math inline">\(t^{\star}_{14} = 1.76\)</span>.
</div>

<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="inference-num.html#cb23-1"></a><span class="co"># use qt() to find the t-cutoff (with 90% in the middle)</span></span>
<span id="cb23-2"><a href="inference-num.html#cb23-2"></a><span class="kw">qt</span>(<span class="fl">0.05</span>, <span class="dt">df =</span> <span class="dv">14</span>)</span>
<span id="cb23-3"><a href="inference-num.html#cb23-3"></a><span class="co">#&gt; [1] -1.76</span></span>
<span id="cb23-4"><a href="inference-num.html#cb23-4"></a><span class="kw">qt</span>(<span class="fl">0.95</span>, <span class="dt">df =</span> <span class="dv">14</span>)</span>
<span id="cb23-5"><a href="inference-num.html#cb23-5"></a><span class="co">#&gt; [1] 1.76</span></span></code></pre></div>
<!--
\begin{onebox}{Confidence interval for a single mean}
  Once you've determined a one-mean confidence interval
  would be helpful for an application,
  there are four steps to constructing the interval:
  \begin{description}
  \item[Prepare.]
      Identify $\bar{x}$, $s$, $n$, and determine what
      confidence level you wish to use.
  \item[Check.]
      Verify the conditions to ensure $\bar{x}$
      is nearly normal.
  \item[Calculate.]
      If the conditions hold, compute $SE$,
      find $t_{df}^{\star}$, and construct the interval.
  \item[Conclude.]
      Interpret the confidence interval in the context
      of the problem.
  \end{description}
\end{onebox}
-->

<div class="guidedpractice">
Using the information and results of the previous Guided Practice and Example, compute a 90% confidence interval for the average mercury content of croaker white fish (Pacific).<a href="#fn133" class="footnote-ref" id="fnref133"><sup>133</sup></a>
</div>


<div class="guidedpractice">
The 90% confidence interval from the previous
Guided Practice is 0.256 ppm to 0.318 ppm.
Can we say that 90% of croaker white fish (Pacific)
have mercury levels between 0.256 and 0.318 ppm?<a href="#fn134" class="footnote-ref" id="fnref134"><sup>134</sup></a>
</div>

<p></p>
</div>
<div id="one-sample-t-tests" class="section level4 unnumbered">
<h4>One sample <span class="math inline">\(t\)</span>-tests</h4>
<p>Now that we’ve used the <span class="math inline">\(t\)</span>-distribution for making a confidence
intervals for a mean, let’s speed on through to
hypothesis tests for the mean.</p>
<!--
\newcommand{\cherryblossomn}{100}
\newcommand{\cherryblossommean}{97.32}
\newcommand{\cherryblossomnull}{93.29}
\newcommand{\cherryblossomsd}{16.98}
\newcommand{\cherryblossomse}{1.70}
\newcommand{\cherryblossomz}{2.37}
-->
<p>Is the typical US runner getting faster or slower over time? We consider this question in the context of the Cherry Blossom Race, which is a 10-mile race in Washington, DC each spring.</p>
<p>The average time for all runners who finished the Cherry Blossom Race in 2006 was 93.29 minutes (93 minutes and about 17 seconds). We want to determine using data from 100 participants in the 2017 Cherry Blossom Race whether runners in this race are getting faster or slower, versus the other possibility that there has been no change.</p>

<div class="guidedpractice">
What are appropriate hypotheses for this context?<a href="#fn135" class="footnote-ref" id="fnref135"><sup>135</sup></a>
</div>


<div class="guidedpractice">
The data come from a simple random sample of all participants,
so the observations are independent.
However, should we be worried about the normality condition?
See Figure <a href="inference-num.html#fig:run10SampTimeHistogram">6.10</a> for a histogram
of the differences and evaluate if we can move
forward.<a href="#fn136" class="footnote-ref" id="fnref136"><sup>136</sup></a>
</div>

<div class="figure" style="text-align: center"><span id="fig:run10SampTimeHistogram"></span>
<img src="06-inference-num_files/figure-html/run10SampTimeHistogram-1.png" alt="A histogram of `time` for the sample Cherry Blossom Race data." width="70%" />
<p class="caption">
Figure 6.10: A histogram of <code>time</code> for the sample Cherry Blossom Race data.
</p>
</div>
<p>When completing a hypothesis test for the one-sample mean,
the process is nearly identical to completing a hypothesis
test for a single proportion.
First, we find the Z score using the observed value,
null value, and standard error;
however, we call it a <strong>T score</strong> since we use
a <span class="math inline">\(t\)</span>-distribution for calculating the tail area.
Then we finding the p-value using the same ideas we used
previously: find the one-tail area under the sampling
distribution, and double it.</p>

<div class="example">
<p>With both the independence
and normality conditions satisfied,
we can proceed with a hypothesis test using
the <span class="math inline">\(t\)</span>-distribution.
The sample mean and sample standard deviation
of the sample
of 100 runners from the
2017 Cherry Blossom Race
are 97.32 and 16.98 minutes,
respectively.
Recall that the sample size is 100
and the average run time in 2006 was 93.29 minutes.
Find the test statistic and p-value.
What is your conclusion?</p>
<hr />
<p>To find the test statistic (T score),
we first must determine the standard error:
<span class="math display">\[\begin{align*}
  SE
    = 16.98 / \sqrt{100}
    = 1.70
  \end{align*}\]</span>
Now we can compute the <strong>T score</strong>
using the sample mean (97.32),
null value (98.29), and <span class="math inline">\(SE\)</span>:
<span class="math display">\[\begin{align*}
  T
    = \frac{97.32 - 93.29}{1.70}
    = 2.37
  \end{align*}\]</span>
For <span class="math inline">\(df = 100 - 1 = 99\)</span>,
we can determine using statistical software
(or a <span class="math inline">\(t\)</span>-table, see below) that the one-tail area is 0.01,
which we double to get the p-value: 0.02.</p>
Because the p-value is smaller than 0.05,
we reject the null hypothesis.
That is, the data provide strong evidence that the average
run time for the Cherry Blossom Run in 2017 is different
than the 2006 average.
Since the observed value is above the null value
and we have rejected the null hypothesis, we would conclude
that runners in the race were slower on average in 2017
than in 2006.
</div>

<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="inference-num.html#cb24-1"></a><span class="co"># using pt() to find the p-value</span></span>
<span id="cb24-2"><a href="inference-num.html#cb24-2"></a><span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="kw">pt</span>(<span class="fl">2.37</span>, <span class="dt">df =</span> <span class="dv">99</span>)</span>
<span id="cb24-3"><a href="inference-num.html#cb24-3"></a><span class="co">#&gt; [1] 0.00986</span></span></code></pre></div>

<div class="onebox">
<p><strong>When using a <span class="math inline">\(t\)</span>-distribution, we use a T score (same as Z score).</strong></p>
To help us remember to use the <span class="math inline">\(t\)</span>-distribution,
we use a <span class="math inline">\(T\)</span> to represent the test statistic,
and we often call this a <strong>T score</strong>.
The Z score and T score are computed in the exact same way
and are conceptually identical:
each represents how many standard errors the observed value
is from the null value.
</div>

<!--
\begin{onebox}{Hypothesis testing for a single mean}
  Once you've determined a one-mean hypothesis test is the
  correct procedure, there are four steps to completing the
  test:
  \begin{description}
  \item[Prepare.]
      Identify the parameter of interest,
      list out hypotheses,
      identify the significance level,
      and identify $\bar{x}$, $s$, and $n$.
  \item[Check.]
      Verify conditions to ensure $\bar{x}$ is nearly normal.
  \item[Calculate.]
      If the conditions hold, compute $SE$,
      compute the T score, and identify the p-value.
  \item[Conclude.]
      Evaluate the hypothesis test by comparing the p-value
      to $\alpha$, and provide a conclusion in the context
      of the problem.
  \end{description}
\end{onebox}
-->
<!--
\CalculatorVideos{confidence intervals and hypothesis tests for a single mean}

-->
</div>
</div>
</div>
<div id="paired-data" class="section level2">
<h2><span class="header-section-number">6.2</span> Paired mean difference</h2>

<div class="onebox">
<p><strong>Notation</strong>.</p>
<ul>
<li><span class="math inline">\(n_{diff}\)</span> = sample size of differences in paired samples</li>
<li><span class="math inline">\(\hat{x}_{diff}\)</span> = sample mean of differences in paired samples</li>
<li><span class="math inline">\(s_{diff}\)</span> = sample standard deviation of differences in paired samples</li>
<li><span class="math inline">\(\mu_{diff}\)</span> = population mean of differences in paired samples</li>
<li><span class="math inline">\(\sigma_{diff}\)</span> = population standard deviation of differences in paired samples
</div></li>
</ul>
<p>Paired data represent a particular type of experimental structure where the analysis is somewhat akin to a one-sample analysis (see Section <a href="inference-num.html#one-mean">6.1</a>) but has other features that resemble a two-sample analysis (see Section <a href="inference-num.html#differenceOfTwoMeans">6.3</a>). As with a two-sample analysis, quantitative measurements are made on each of two different levels of the explanatory variable. However, because the observational unit is <strong>paired</strong> across the two groups, the two measurements are subtracted such that only the difference is retained. Table <a href="inference-num.html#tab:pairedexamples">6.2</a> presents some examples of studies where paired designs were implemented.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:pairedexamples">Table 6.2: </span>Examples of studies where a paired design is used to measure the difference in the measurement over two conditions.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Observational unit
</th>
<th style="text-align:left;">
Comparison groups
</th>
<th style="text-align:left;">
Measurement
</th>
<th style="text-align:left;">
Value of interest
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Car
</td>
<td style="text-align:left;">
Brand A vs Brand B
</td>
<td style="text-align:left;">
amount of tire tread after 1,000 miles
</td>
<td style="text-align:left;">
difference in tread
</td>
</tr>
<tr>
<td style="text-align:left;">
Textbook
</td>
<td style="text-align:left;">
UCLA vs Amazon
</td>
<td style="text-align:left;">
price of new text
</td>
<td style="text-align:left;">
difference in price
</td>
</tr>
<tr>
<td style="text-align:left;">
Individual person
</td>
<td style="text-align:left;">
Pre-course vs Post-course
</td>
<td style="text-align:left;">
exam score
</td>
<td style="text-align:left;">
difference in score
</td>
</tr>
</tbody>
</table>

<div class="onebox">
<p><strong>Paired data.</strong></p>
Two sets of observations are <em>paired</em> if each
observation in one set has a special correspondence
or connection with exactly one observation in the other
data set.
</div>

<div id="randomization-test-for-h_0-mu_d-0" class="section level3">
<h3><span class="header-section-number">6.2.1</span> Randomization test for <span class="math inline">\(H_0: \mu_d = 0\)</span></h3>
<p>Consider an experiment done to measure whether tire brand A or tire brand B has longer wear. That is, after 1,000 miles on a car, which brand of tires has more tread, on average?</p>
<div id="observed-data-1" class="section level5 unnumbered">
<h5>Observed data</h5>
<p>The observed data represent 25 tread measurements taken on 25 tires of Brand A and 25 tires of Brand B.
The study used a total of 25 cars, so on each car, one tire was of Brand A and one was of Brand B.
Figure <a href="inference-num.html#fig:tiredata">6.11</a> presents the observed data.
The Brand A manufacturer looks at the box plot below and says:
&gt; clearly the tread on Brand A tires is higher, on average, than the tread on Brand B tires after 1,000 miles of driving.</p>
<p>The Brand B manufacturer is skeptical and retorts:<br />
&gt; but with only 25 cars, it seems that the variability in road conditions (sometimes on tire hits a pothole, etc.) could be what leads to the small difference in average tread amount.</p>
<p>We’d like to be able to systematically distinguish between what manufacturer A sees in the plot and what manufacturer B sees in the plot. Fortunately for us, we have an excellent way to simulate the natural variability (from road conditions, etc.) that can lead to tires being worn at different rates.</p>
<div class="figure" style="text-align: center"><span id="fig:tiredata"></span>
<img src="06-inference-num_files/figure-html/tiredata-1.png" alt="Boxplots of the tire tread data and the brand of tire from which the original measurements came." width="70%" />
<p class="caption">
Figure 6.11: Boxplots of the tire tread data and the brand of tire from which the original measurements came.
</p>
</div>
</div>
<div id="variability-of-the-statistic-1" class="section level5 unnumbered">
<h5>Variability of the statistic</h5>
<p>A randomization test will identify whether the differences seen in the box plot below could have happened just by chance variability.
As before, we will simulate the variability in the study under the assumption that the null hypothesis is true.
In this study, the null hypothesis is that average tire tread wear is the same across Brand A and Brand B tires.</p>
<ul>
<li><span class="math inline">\(H_0: \mu_A = \mu_B\)</span>, the average tread wear is the same for the two tire brands.<br />
</li>
<li><span class="math inline">\(H_A: \mu_A \ne \mu_B\)</span>, the average tread wear is different across the two tire brands.</li>
</ul>
<p>Figure <a href="inference-num.html#fig:pairrand">6.12</a> describes how the tread values can be simulated under the null hypothesis.
Remember, if the null hypothesis is true, it will not matter which brand is put on which tire because the overall tread wear will be the same across pairs.</p>
<div class="figure" style="text-align: center"><span id="fig:pairrand"></span>
<img src="06/figures/pairrand.png" alt="process of randomizing across pairs." width="75%" />
<p class="caption">
Figure 6.12: process of randomizing across pairs.
</p>
</div>
<p>After randomizing the tire brand to the tread measurements under the null hypothesis, a new boxplot summarizes the randomized data.<br />
Figure <a href="inference-num.html#fig:tiredatarand1">6.13</a> presents one randomization of the data.
Notice how the same two observations are linked by a grey line, but some of the tread values have been randomly assigned to the opposite tire brand than they were originally (while some are still connected to their original tire brands).</p>
<div class="figure" style="text-align: center"><span id="fig:tiredatarand1"></span>
<img src="06-inference-num_files/figure-html/tiredatarand1-1.png" alt="One randomization where the brand is randomly swapped (or not) across the two tread wear measurements from the same car." width="70%" />
<p class="caption">
Figure 6.13: One randomization where the brand is randomly swapped (or not) across the two tread wear measurements from the same car.
</p>
</div>
<p>Figure <a href="inference-num.html#fig:tiredatarand2">6.14</a> presents yet another randomization of the data.
Again, the same observations are linked by a grey line, and some of the tread values have been randomly assigned to the opposite tire brand than they were originally (while some are still connected to their original tire brands).</p>
<div class="figure" style="text-align: center"><span id="fig:tiredatarand2"></span>
<img src="06-inference-num_files/figure-html/tiredatarand2-1.png" alt="An additional randomization where the brand is randomly swapped (or not) across the two tread wear measurements from the same car." width="70%" />
<p class="caption">
Figure 6.14: An additional randomization where the brand is randomly swapped (or not) across the two tread wear measurements from the same car.
</p>
</div>
</div>
<div id="observed-statistic-vs.-null-statistics" class="section level5 unnumbered">
<h5>Observed statistic vs. null statistics</h5>
<p>By repeating the randomization process, we can create a distribution of the average of the differences in tire treads, as seen in Figure <a href="inference-num.html#fig:pairRandomiz">6.16</a>.
As expected (because the differences were generated under the null hypothesis), the center of the histogram is zero.
A line has been drawn at the observed difference which is nowhere near the differences simulated from natural variability by mixing up which the tire received brand A and which received brand B.
Because the observed statistic is so far away from the natural variability of the randomized differences, we believe that there is a significant difference between brand A and brand B.
Our conclusion is that the extra amount of average tire tread in brand A is due to more than just natural variability: we reject <span class="math inline">\(H_0\)</span> and conclude that <span class="math inline">\(\mu_A &gt; \mu_B\)</span>.</p>

<div class="todo">
need an actual p-value here, probably shade the tails of the graph, too
</div>

<div class="figure" style="text-align: center"><span id="fig:pairrandfull"></span>
<img src="06/figures/pairrandfull.png" alt="process of randomizing across pairs." width="75%" />
<p class="caption">
Figure 6.15: process of randomizing across pairs.
</p>
</div>
<div class="figure" style="text-align: center"><span id="fig:pairRandomiz"></span>
<img src="06-inference-num_files/figure-html/pairRandomiz-1.png" alt="Histogram of 1000 differences with tire brand randomly assigned across the two observations per pair." width="70%" />
<p class="caption">
Figure 6.16: Histogram of 1000 differences with tire brand randomly assigned across the two observations per pair.
</p>
</div>
</div>
</div>
<div id="bootstrap-confidence-interval-for-mu_d" class="section level3">
<h3><span class="header-section-number">6.2.2</span> Bootstrap confidence interval for <span class="math inline">\(\mu_d\)</span></h3>
<p>For both the bootstrap and the mathematical models applied to paired data, the analysis is virtually identical to the one-sample approach given in Section <a href="inference-num.html#one-mean">6.1</a>.
The key to working with paired data (for bootstrapping and mathematical approaches) is to consider the measurement of interest to be the difference in measured values across the pair of observations.</p>
<div id="observed-data-2" class="section level5 unnumbered">
<h5>Observed data</h5>
<p>In an earlier edition of this textbook,
we found that Amazon prices were, on average,
lower than those of the UCLA Bookstore for UCLA courses
in 2010.
It’s been several years, and many stores have adapted
to the online market, so we wondered,
how is the UCLA Bookstore doing today?</p>
<p>We sampled 201 UCLA courses.
Of those, 68
required books could be found on Amazon.
A portion of the data set from these courses
is shown in Figure <a href="inference-num.html#tab:textbooksDF">6.3</a>,
where prices are in US dollars.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:textbooksDF">Table 6.3: </span>Four cases of the <code>ucla_textbooks_f18</code> dataset.
</caption>
<thead>
<tr>
<th style="text-align:left;">
subject
</th>
<th style="text-align:left;">
course_num
</th>
<th style="text-align:right;">
bookstore_new
</th>
<th style="text-align:right;">
amazon_new
</th>
<th style="text-align:right;">
price_diff
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
American Indian Studies
</td>
<td style="text-align:left;">
M10
</td>
<td style="text-align:right;">
48.0
</td>
<td style="text-align:right;">
47.5
</td>
<td style="text-align:right;">
0.52
</td>
</tr>
<tr>
<td style="text-align:left;">
Anthropology
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:right;">
14.3
</td>
<td style="text-align:right;">
13.6
</td>
<td style="text-align:right;">
0.71
</td>
</tr>
<tr>
<td style="text-align:left;">
Arts and Architecture
</td>
<td style="text-align:left;">
10
</td>
<td style="text-align:right;">
13.5
</td>
<td style="text-align:right;">
12.5
</td>
<td style="text-align:right;">
0.97
</td>
</tr>
<tr>
<td style="text-align:left;">
Asian
</td>
<td style="text-align:left;">
M60W
</td>
<td style="text-align:right;">
49.3
</td>
<td style="text-align:right;">
55.0
</td>
<td style="text-align:right;">
-5.69
</td>
</tr>
</tbody>
</table>
<!--
\newcommand{\uclabookN}{68}
\newcommand{\uclabookDF}{67}
\newcommand{\uclabookM}{3.58}
\newcommand{\uclabookSD}{13.42}
\newcommand{\uclabookSE}{1.63}
-->
<p>
</p>
<p>Each textbook has two corresponding prices in the data set:
one for the UCLA Bookstore and one for Amazon.
When two sets of observations have this special
correspondence, they are said to be <strong>paired</strong>.</p>
</div>
<div id="variability-of-the-statistic-2" class="section level5 unnumbered">
<h5>Variability of the statistic</h5>
<p>Following the example of bootstrapping the one-sample statistic, the observed differences can be bootstrapped in order to understand the variability of the average difference from sample to sample.</p>
<div class="figure" style="text-align: center"><span id="fig:bootdiff1"></span>
<img src="06/figures/bootquant3.png" alt="a figure similar to this but with differences in prices (books????) as the unit to bootstrap." width="75%" />
<p class="caption">
Figure 6.17: a figure similar to this but with differences in prices (books????) as the unit to bootstrap.
</p>
</div>
<p>In Figure <a href="inference-num.html#fig:pairboot">6.18</a>, two 99% confidence intervals for the difference in the cost of a new book at the UCLA bookstore compared with Amazon have been calculated.
The bootstrap percentile interval is computing using the 0.5 percentile and 99.5 percentile bootstrapped differences and is found to be ($ 0.25, $ 7.87).
The bootstrap SE interval is found by computing the SE of the bootstrapped differences (<span class="math inline">\(s_{diff} = \$1.64\)</span>) and the normal multiplier of <span class="math inline">\(z^* = 2.58\)</span>. The averaged difference is <span class="math inline">\(\bar{x} = \$3.58\)</span>.
The 99% confidence interval is: $ $3.58 2.58 $ 1.64 ($-0.65, $7.81)$.
The confidence intervals seem to indicate that the UCLA bookstore price is, on average, higher than the Amazon price.
However, if the analysis required a strong degree of certainty (e.g., 99% confidence), and the bootstrap SE interval was most appropriate (given a second course in statistics the nuances of the methods were investigated), the results of which book seller is higher is not well determined.
That is, the 99% bootstrap SE interval gives potential for UCLA to be lower, on average, than Amazon (because of the possible negative values for the true mean difference in price).</p>
<pre><code>#&gt; # A tibble: 1 x 2
#&gt;   lower_ci upper_ci
#&gt;      &lt;dbl&gt;    &lt;dbl&gt;
#&gt; 1    0.108     8.32
#&gt; # A tibble: 1 x 2
#&gt;   lower_ci upper_ci
#&gt;      &lt;dbl&gt;    &lt;dbl&gt;
#&gt; 1   -0.652     7.82</code></pre>
<div class="figure" style="text-align: center"><span id="fig:pairboot"></span>
<img src="06-inference-num_files/figure-html/pairboot-1.png" alt="Bootstrap distribution for the average difference in new book price at the UCLA bookstore versus Amazon.  99% confidence intervals are superimposed using blue (bootstrap percentile interval) and green (bootstrap SE interval) lines." width="70%" />
<p class="caption">
Figure 6.18: Bootstrap distribution for the average difference in new book price at the UCLA bookstore versus Amazon. 99% confidence intervals are superimposed using blue (bootstrap percentile interval) and green (bootstrap SE interval) lines.
</p>
</div>
</div>
</div>
<div id="mathematical-model" class="section level3">
<h3><span class="header-section-number">6.2.3</span> Mathematical model</h3>
<p>Thinking about the differences as a single observation on an observational unit changes the paired setting into the one-sample setting.
The mathematical model for the one-sample case is covered in Section <a href="inference-num.html#one-mean-math">6.1.2</a>.</p>
<div id="observed-data-3" class="section level5 unnumbered">
<h5>Observed data</h5>
<p>To analyze paired data, it is often useful to look
at the difference in outcomes of each pair of observations.
In the textbook data, we look at the differences
in prices, which is represented as the
<code>price_difference</code> variable
in the data set.
Here the differences are taken as
<span class="math display">\[\begin{align*}
\text{UCLA Bookstore price} - \text{Amazon price}
\end{align*}\]</span></p>
<p>It is important that we always subtract using
a consistent order;
here Amazon prices are always subtracted from UCLA prices.
The first difference shown in Table <a href="inference-num.html#tab:textbooksDF">6.3</a>
is computed as <span class="math inline">\(47.97 - 47.45 = 0.52\)</span>.
Similarly, the second difference is computed as
<span class="math inline">\(14.26 - 13.55 = 0.71\)</span>,
and the third is <span class="math inline">\(13.50 - 12.53 = 0.97\)</span>.
A histogram of the differences is shown in
Figure <a href="inference-num.html#fig:diffInTextbookPricesF18">6.19</a>.
Using differences between paired observations
is a common and useful way to analyze paired data.</p>
<div class="figure" style="text-align: center"><span id="fig:diffInTextbookPricesF18"></span>
<img src="06-inference-num_files/figure-html/diffInTextbookPricesF18-1.png" alt="Histogram of the difference in price for each book sampled." width="70%" />
<p class="caption">
Figure 6.19: Histogram of the difference in price for each book sampled.
</p>
</div>
</div>
<div id="variability-of-the-statistic-3" class="section level5 unnumbered">
<h5>Variability of the statistic</h5>
<p>To analyze a paired data set,
we simply analyze the differences.
We can use the same <span class="math inline">\(t\)</span>-distribution techniques
we applied in
Section <a href="inference-num.html#one-mean-math">6.1.2</a>.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:textbooksSummaryStats">Table 6.4: </span>Summary statistics for the 68 price differences.
</caption>
<thead>
<tr>
<th style="text-align:right;">
<span class="math inline">\(n_{diff}\)</span>
</th>
<th style="text-align:right;">
<span class="math inline">\(\bar{x}_{diff}\)</span>
</th>
<th style="text-align:right;">
<span class="math inline">\(s_{diff}\)</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
68
</td>
<td style="text-align:right;">
3.58
</td>
<td style="text-align:right;">
13.4
</td>
</tr>
</tbody>
</table>

<div class="example">
<p>Set up a hypothesis test
to determine whether, on average, there is a difference
between Amazon’s price for a book and the UCLA
bookstore’s price.
Also, check the conditions for whether we can move
forward with the test using the <span class="math inline">\(t\)</span>-distribution.</p>
<hr />
<p>We are considering two scenarios: there is no difference
or there is some difference in average prices.</p>
<ul>
<li><p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_{diff} = 0\)</span>.
There is no difference in the average textbook price.</p></li>
<li><p><span class="math inline">\(H_A\)</span>: <span class="math inline">\(\mu_{diff} \neq 0\)</span>.
There is a difference in average prices.</p>
<p>Next, we check the independence and normality conditions.
The observations are based on a simple random sample,
so independence is reasonable.
While there are some outliers,
<span class="math inline">\(n = 68\)</span> and none of the outliers
are particularly extreme, so the normality
of <span class="math inline">\(\bar{x}\)</span> is satisfied.
With these conditions satisfied,
we can move forward with the <span class="math inline">\(t\)</span>-distribution.</p>
</div></li>
</ul>
</div>
<div id="observed-statistic-vs.-null-statistics-1" class="section level5 unnumbered">
<h5>Observed statistic vs. null statistics</h5>
<p>As mentioned previously, the methods applied to a difference will be identical to the one-sample techniques. Therefore, the full hypothesis test framework is given as an example.</p>

<div class="example">
<p>Complete the hypothesis test started
in the previous Example.</p>
<hr />
<p>To compute the test compute the standard error associated with
<span class="math inline">\(\bar{x}_{diff}\)</span> using the standard
deviation of the differences
(<span class="math inline">\(s_{diff} = 13.42\)</span>)
and the number of differences
(<span class="math inline">\(n_{diff} = 68\)</span>):
<span class="math display">\[\begin{align*}
  SE_{\bar{x}_{diff}}
    = \frac{s_{diff}}{\sqrt{n_{diff}}}
    = \frac{13.42}{\sqrt{68}} = 1.63
  \end{align*}\]</span>
The test statistic is the T-score of
<span class="math inline">\(\bar{x}_{diff}\)</span>
under the null condition that the actual mean
difference is 0:
<span class="math display">\[\begin{align*}
  T
    = \frac{\bar{x}_{diff} - 0}
        {SE_{x_{diff}}}
    = \frac{3.58 - 0}{1.63} = 2.20
  \end{align*}\]</span>
To visualize the p-value, the sampling distribution
of <span class="math inline">\(\bar{x}_{diff}\)</span> is drawn as though
<span class="math inline">\(H_0\)</span> is true,
and the p-value is represented by the two shaded tails in Figure <a href="inference-num.html#fig:textbooksF18HTTails">6.20</a>.</p>
<p>The degrees of freedom is
<span class="math inline">\(df = 68 - 1 = 67\)</span>.
Using statistical software, we find the
one-tail area of 0.0156.
Doubling this area gives the p-value: 0.0312.</p>
Because the p-value is less than 0.05,
we reject the null hypothesis.
Amazon prices are, on average, lower than the
UCLA Bookstore prices for UCLA courses.
</div>

<div class="figure" style="text-align: center"><span id="fig:textbooksF18HTTails"></span>
<img src="06-inference-num_files/figure-html/textbooksF18HTTails-1.png" alt="Distribution of $\bar{x}_{diff}$ under the null hypothesis of no difference.  The observed average difference of 2.98 is marked with the shaded areas more extreme than the observed difference given as the p-value." width="70%" />
<p class="caption">
Figure 6.20: Distribution of <span class="math inline">\(\bar{x}_{diff}\)</span> under the null hypothesis of no difference. The observed average difference of 2.98 is marked with the shaded areas more extreme than the observed difference given as the p-value.
</p>
</div>

<div class="guidedpractice">
<p>Create a 95% confidence interval for the average price difference between books at the UCLA bookstore and books on Amazon.^[Conditions
have already verified and the standard error
computed in a previous Example.</p>
To find the confidence interval,
identify <span class="math inline">\(t^{\star}_{67}\)</span> using statistical software
or the <span class="math inline">\(t\)</span>-table (<span class="math inline">\(t^{\star}_{67} = 2.00)\)</span>,
and plug it, the point estimate,
and the standard error into the confidence
interval formula:
<span class="math display">\[\begin{align*}
  \text{point estimate} \ \pm\ z^{\star} \times SE
      \quad\to\quad
          3.58 \ \pm\ 2.00 \times 1.63
      \quad\to\quad (0.32 6.84)
  \end{align*}\]</span>
We are 95% confident that Amazon is, on average,
between $0.32 and $6.84 less expensive
than the UCLA Bookstore for UCLA course books.]
</div>


<div class="guidedpractice">
<p>We have strong evidence that Amazon is,
on average, less expensive.
How should this conclusion affect UCLA student
buying habits?
Should UCLA students always buy their books
on Amazon?^[The average price difference
is only mildly useful for this question.
Examine the distribution shown in
Figure <a href="inference-num.html#fig:diffInTextbookPricesF18">6.19</a>.
There are certainly a handful of cases where
Amazon prices are far below the UCLA Bookstore’s,
which suggests it is worth checking Amazon
(and probably other online sites) before purchasing.
However, in many cases the Amazon price is
above what the UCLA Bookstore charges,
and most of the time the price isn’t that different.
Ultimately, if getting a book immediately from
the bookstore is notably more convenient,
e.g. to get started on reading or homework,
it’s likely a good idea to go with the UCLA
Bookstore unless the price difference on a
specific book happens to be quite large.</p>
For reference, this is a very different result
from what we (the authors) had seen in a similar
data set from 2010.
At that time, Amazon prices were almost uniformly
lower than those of the UCLA Bookstore’s and by
a large margin, making the case to use Amazon over
the UCLA Bookstore quite compelling at that time.
Now we frequently check multiple websites
to find the best price.]
</div>

<p>
</p>
</div>
</div>
</div>
<div id="differenceOfTwoMeans" class="section level2">
<h2><span class="header-section-number">6.3</span> Difference of two means</h2>

<div class="onebox">
<p><strong>Notation</strong>.</p>
<ul>
<li><span class="math inline">\(n_1\)</span>, <span class="math inline">\(n_2\)</span> = sample sizes of two independent samples</li>
<li><span class="math inline">\(\bar{x}_1\)</span>, <span class="math inline">\(\bar{x}_2\)</span> = sample means of two independent samples</li>
<li><span class="math inline">\(s_1\)</span>, <span class="math inline">\(s_2\)</span> = sample standard deviations of two independent samples</li>
<li><span class="math inline">\(\mu_1\)</span>, <span class="math inline">\(\mu_2\)</span> = population means of two independent samples</li>
<li><span class="math inline">\(\sigma_1\)</span>, <span class="math inline">\(\sigma_2\)</span> = population standard deviations of two independent samples
</div></li>
</ul>
<p>In this section we consider a difference in
two population means, <span class="math inline">\(\mu_1 - \mu_2\)</span>, under the condition
that the data are not paired.
Just as with a single sample, we identify conditions to ensure
we can use the <span class="math inline">\(t\)</span>-distribution with a point estimate
of the difference, <span class="math inline">\(\bar{x}_1 - \bar{x}_2\)</span>,
and a new standard error formula.</p>
<p>The details for working through inferential problems in the two independent means setting are strikingly similar to those applied to the two independent proportions stetting.
We first cover a randomization test where the observations are shuffled under the assumption that the null hypothesis is true.
Then we bootstrap the data (with no imposed null hypothesis) to create a confidence interval for the true difference in population means, <span class="math inline">\(\mu_1 - \mu_2\)</span>.
The mathematical model, here the <span class="math inline">\(t\)</span>-distribution, is able to describe both the randomization test and the boostrapping as long as the conditions are met.</p>
<p>The inferential tools are applied to three different data contexts: determining whether
stem cells can improve heart function,
exploring the relationship between pregnant women’s smoking
habits and birth weights of newborns,
and exploring whether there is statistically significant
evidence that one variation of an exam is harder than
another variation.
This section is motivated by questions like
“Is there convincing evidence that newborns from mothers
who smoke have a different average birth weight than newborns
from mothers who don’t smoke?”</p>
<div id="rand2mean" class="section level3">
<h3><span class="header-section-number">6.3.1</span> Randomization test for <span class="math inline">\(H_0: \mu_1 - \mu_2 = 0\)</span></h3>
<p></p>
<p>An instructor decided to run two slight variations of the same exam. Prior to passing out the exams, she shuffled the exams together to ensure each student received a random version. Summary statistics for how students performed on these two exams are shown in Table <a href="inference-num.html#tab:summaryStatsForTwoVersionsOfExams">6.5</a> and plotted in Figure <a href="inference-num.html#fig:boxplotTwoVersionsOfExams">6.21</a>. Anticipating complaints from students who took Version B, she would like to evaluate whether the difference observed in the groups is so large that it provides convincing evidence that Version B was more difficult (on average) than Version A.</p>
<div id="observed-data-4" class="section level5 unnumbered">
<h5>Observed data</h5>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:summaryStatsForTwoVersionsOfExams">Table 6.5: </span>Summary statistics of scores for each exam version.
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
<span class="math inline">\(n\)</span>
</th>
<th style="text-align:right;">
<span class="math inline">\(\bar{x}\)</span>
</th>
<th style="text-align:right;">
s
</th>
<th style="text-align:right;">
minimum
</th>
<th style="text-align:right;">
maximum
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
A
</td>
<td style="text-align:right;">
58
</td>
<td style="text-align:right;">
75.1
</td>
<td style="text-align:right;">
13.9
</td>
<td style="text-align:right;">
44
</td>
<td style="text-align:right;">
100
</td>
</tr>
<tr>
<td style="text-align:left;">
B
</td>
<td style="text-align:right;">
55
</td>
<td style="text-align:right;">
72.0
</td>
<td style="text-align:right;">
13.8
</td>
<td style="text-align:right;">
38
</td>
<td style="text-align:right;">
100
</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span id="fig:boxplotTwoVersionsOfExams"></span>
<img src="06-inference-num_files/figure-html/boxplotTwoVersionsOfExams-1.png" alt="Exam scores for students given one of three different exams." width="70%" />
<p class="caption">
Figure 6.21: Exam scores for students given one of three different exams.
</p>
</div>

<div class="guidedpractice">
Construct hypotheses to evaluate whether the observed
difference in sample means, <span class="math inline">\(\bar{x}_A - \bar{x}_B=3.1\)</span>,
is due to chance. We will later evaluate these hypotheses
using <span class="math inline">\(\alpha = 0.01\)</span>.<a href="#fn137" class="footnote-ref" id="fnref137"><sup>137</sup></a>
</div>


<div class="guidedpractice">
Before moving on to evaluate the hypotheses in the previous Guided Practice, let’s think carefully about the dataset. Are the observations across the two groups independent? Are there any concerns about outliers?<a href="#fn138" class="footnote-ref" id="fnref138"><sup>138</sup></a>
</div>

</div>
<div id="variability-of-the-statistic-4" class="section level5 unnumbered">
<h5>Variability of the statistic</h5>

<div class="todo">
need to talk about the way to randomize is almost identical to chapter 5 &amp; 6. a new plot will probably help (but again, very similar to 5.7)
</div>

<p>In Section <a href="inference-cat.html#two-prop-errors">5.4.1</a>, the variability of the statistic (previously: <span class="math inline">\(\hat{p}_1 - \hat{p}_2\)</span>) was visualized after shuffling the observations across the two treatment groups many times.
The shuffling process implements the null hypothesis model (that there is no effect of the treatment).
In the exam example, the null hypothesis is that exam A and exam B are equally difficult, so the average scores across the two tests should be the same.
If the exams were equally difficult, <em>due to natural variability</em>, we would sometimes expect students to do slightly better on exam A (<span class="math inline">\(\bar{x}_A &gt; \bar{x}_B\)</span>) and sometimes expect students to do slightly better on exam B (<span class="math inline">\(\bar{x}_B &gt; \bar{x}_A\)</span>).
The question at hand is: does <span class="math inline">\(\bar{x}_A - \bar{x}_B=3.1\)</span> indicate that exam A is easier than exam B.</p>
<p>Figure <a href="inference-num.html#fig:rand2means">6.22</a> shows the process of randomizing the exam to the observed exam scores.
If the null hypothesis is true, then the score on each exam should represent the true student ability on that material.
It shouldn’t matter whether they were given exam A or exam B.
By reallocating which student got which exam, we are able to understand how the difference in average exam scores changes due only to natural variability.
There is only one iteration of the randomization process in Figure <a href="inference-num.html#fig:rand2means">6.22</a>, leading to one simulated difference in average scores.</p>
<div class="figure" style="text-align: center"><span id="fig:rand2means"></span>
<img src="06/figures/rand2means.png" alt="The version of the test (A or B) is randomly allocated to the test scores, under the null assumption that the tests are equally difficult." width="75%" />
<p class="caption">
Figure 6.22: The version of the test (A or B) is randomly allocated to the test scores, under the null assumption that the tests are equally difficult.
</p>
</div>
<p>Building on Figure <a href="inference-num.html#fig:rand2means">6.22</a>, Figure <a href="inference-num.html#fig:randexams">6.23</a> shows the values of the simulated statistics <span class="math inline">\(\bar{x}_{1, sim} - \bar{x}_{2, sim}\)</span> over 1000 random simulations.
We see that, just by chance, the difference in scores can range anywhere from -10 points to +10 points.</p>
<div class="figure" style="text-align: center"><span id="fig:randexams"></span>
<img src="06-inference-num_files/figure-html/randexams-1.png" alt="Histogram of differences in means, calculated from 1000 different randomizations of the exam types." width="70%" />
<p class="caption">
Figure 6.23: Histogram of differences in means, calculated from 1000 different randomizations of the exam types.
</p>
</div>
</div>
<div id="observed-statistic-vs.-null-statistics-2" class="section level5 unnumbered">
<h5>Observed statistic vs. null statistics</h5>
<p>The goal of the randomization test is to assess the observed data, here the statistic of interest is <span class="math inline">\(\bar{x}_A - \bar{x}_B=3.1\)</span>.
The randomization distribution allows us to identify whether a difference of 3.1 points is more than one would expect by natural variability.
By plotting the value of 3.1 on Figure <a href="inference-num.html#fig:randexamspval">6.24</a>, we can measure how different or similar 3.1 is to the randomized differences which were generated under the null hypothesis.</p>
<div class="figure" style="text-align: center"><span id="fig:randexamspval"></span>
<img src="06-inference-num_files/figure-html/randexamspval-1.png" alt="Histogram of differences in means, calculated from 1000 different randomizations of the exam types.  The observed difference of 3.1 points is plotted as a vertical line, and the area more extreme than 3.1 is shaded to represent the p-value." width="70%" />
<p class="caption">
Figure 6.24: Histogram of differences in means, calculated from 1000 different randomizations of the exam types. The observed difference of 3.1 points is plotted as a vertical line, and the area more extreme than 3.1 is shaded to represent the p-value.
</p>
</div>

<div class="example">
<p>Approximate the p-value depicted in Figure <a href="inference-num.html#fig:randexamspval">6.24</a>, and provide a conclusion in the context of the case study.</p>
<hr />
<p>Using software, we can find the number of shuffled differences in means that are less than the observed difference (of 3.14) is 19 (our of 1000 randomizations). So 10% of the simulations are larger than the observed difference. To get the p-value, we double the proportion of randomized differences which are larger than the observed difference, p-value = 0.2.</p>
Previously, we specified that we would use <span class="math inline">\(\alpha = 0.01\)</span>.
Since the p-value is larger than <span class="math inline">\(\alpha\)</span>,
we do not reject the null hypothesis.
That is, the data do not convincingly show that one exam
version is more difficult than the other, and the teacher
should not be convinced that she should add points to the
Version B exam scores.
</div>

<pre><code>#&gt; # A tibble: 1 x 1
#&gt;   p_value
#&gt;     &lt;dbl&gt;
#&gt; 1     0.1</code></pre>
<p>The large p-value and consistency of <span class="math inline">\(\bar{x}_A - \bar{x}_B=3.1\)</span> with the randomized differences leads us to <em>not reject the null hypothesis</em>. Said differently, there is no evidence to think that one of the tests is easier than the other.
One might be inclined to conclude that the tests have the same level of difficulty, but that conclusion would be wrong.
The hypothesis testing framework is set up only to reject a null claim, it is not set up to validate a null claim.
As we concluded, the data are consistent with exams A and B being equally difficult, but the data are also consistent with exam A being 3.1 points “easier” than exam B.
The data are not able to adjudicate on whether the exams are equally hard or whether one of them is slightly easier.
Indeed, conclusions where the null hypothesis is not rejected often seem unsatisfactory.
However, in this case, the teacher and class are probably all relieved that there is no evidence to demonstrate that one of the exams is more difficult than the other.</p>
<!--
Below is the t-test for the example above using a randomization test.  Doesn't seem like we need both.


After verifying the conditions for each sample and confirming the samples are independent of each other, we are ready to conduct the test using the $t$-distribution. In this case, we are estimating the true difference in average test scores using the sample data, so the point estimate is $\bar{x}_A - \bar{x}_B = 3.1$. The standard error of the estimate can be calculated as
\begin{align*}
SE
  = \sqrt{\frac{s_A^2}{n_A} + \frac{s_B^2}{n_B}}
  = \sqrt{\frac{14^2}{30} + \frac{20^2}{27}}
  = 4.62
\end{align*}
Finally, we construct the test statistic:
\begin{align*}
T
  = \frac{\text{point estimate} - \text{null value}}{SE}
  = \frac{(79.4-74.1) - 0}{4.62}
  = 1.15
\end{align*}
If we have a computer handy, we can identify the degrees
of freedom as 45.97.
Otherwise we use the smaller of $n_1-1$ and $n_2-1$: $df=26$.

\D{\newpage}

\begin{figure}[h]
  \centering
  \Figure{0.63}{pValueOfTwoTailAreaOfExamVersionsWhereDFIs26}
  \caption{The $t$-distribution with 26 degrees of freedom
      and the p-value from exam example represented
      as the shaded areas.}
  \label{pValueOfTwoTailAreaOfExamVersionsWhereDFIs26}
\end{figure}

\begin{examplewrap}
\begin{nexample}{Identify the p-value depicted in
    Figure \ref{pValueOfTwoTailAreaOfExamVersionsWhereDFIs26}
    using $df = 26$, and provide a conclusion in the
    context of the case study.}
  Using software, we can find the one-tail area (0.13)
  and then double this value to get the two-tail area,
  which is the p-value: 0.26.
  (Alternatively, we could use the $t$-table in
  Appendix \ref{tDistributionTable}.)

  In Guided
  Practice \ref{htSetupForEvaluatingTwoExamVersions},
  we specified that we would use $\alpha = 0.01$.
  Since the p-value is larger than $\alpha$,
  we do not reject the null hypothesis.
  That is, the data do not convincingly show that one exam
  version is more difficult than the other, and the teacher
  should not be convinced that she should add points to the
  Version B exam scores.
\end{nexample}
\end{examplewrap}
-->
<p></p>
</div>
</div>
<div id="bootstrap-confidence-interval-for-mu_1---mu_2" class="section level3">
<h3><span class="header-section-number">6.3.2</span> Bootstrap confidence interval for <span class="math inline">\(\mu_1 - \mu_2\)</span></h3>
<p>
</p>
<p>Does treatment using embryonic stem cells (ESCs)
help improve heart function following a heart attack?
Table <a href="inference-num.html#tab:statsSheepEscStudy">6.6</a> contains summary statistics
for an experiment to test ESCs in sheep that had a heart attack.
Each of these sheep was randomly assigned to the ESC
or control group, and the change in their hearts’ pumping
capacity was measured in the study.
Figure <a href="inference-num.html#fig:stemCellTherapyForHearts">6.29</a> provides
histograms of the two data sets.
A positive value corresponds to increased pumping capacity,
which generally suggests a stronger recovery.
Our goal will be to identify a 95% confidence interval
for the effect of ESCs on the change in heart pumping
capacity relative to the control group.</p>
<div id="observed-data-5" class="section level5 unnumbered">
<h5>Observed data</h5>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:statsSheepEscStudy">Table 6.6: </span>Summary statistics of the embryonic stem cell study.
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
<span class="math inline">\(n\)</span>
</th>
<th style="text-align:right;">
<span class="math inline">\(\bar{x}\)</span>
</th>
<th style="text-align:right;">
s
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
ESCs
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
3.50
</td>
<td style="text-align:right;">
5.17
</td>
</tr>
<tr>
<td style="text-align:left;">
control
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
-4.33
</td>
<td style="text-align:right;">
2.76
</td>
</tr>
</tbody>
</table>
<p>The point estimate of the difference in the heart pumping variable
is straightforward to find: it is the difference in the sample means.
<span class="math display">\[\begin{align*}
\bar{x}_{esc} - \bar{x}_{control}\ 
  =\ 3.50 - (-4.33)\ 
  =\ 7.83
\end{align*}\]</span></p>
</div>
<div id="variability-of-the-statistic-5" class="section level5 unnumbered">
<h5>Variability of the statistic</h5>
<p>As we saw in Section <a href="inference-cat.html#two-prop-boot-ci">5.4.2</a>, we will use bootstrapping to estimate the variability associated with the difference in sample means when taking repeated samples. In a method akin to two proportions, a <em>separate</em> sample is taken with replacement from each group (here ESCs and control), the sample means are calculated, and their difference is taken. The entire process is repeated multiple times to produce a bootstrap distribution of the difference in sample means (<em>without</em> the null hypothesis assumption).</p>
<p>Figure <a href="inference-num.html#fig:bootexamsci">6.26</a> displays the variability of the differences in means with the 90% percentile and SE CIs super imposed.</p>

<div class="todo">
<p>one we have the whole example, write up a bit about how the two different intervals are constructed (including the calculated value of the SE of the difference in means)</p>
with the cars, we can compare two different cities. link each bootstrap sample, create the interval, etc.
</div>

<div class="figure" style="text-align: center"><span id="fig:boot2mean"></span>
<img src="06/figures/boot2mean.png" alt="first figure with the ? pop, then sample, then estimate of the pop. need to re-do with cars" width="75%" />
<p class="caption">
Figure 6.25: first figure with the ? pop, then sample, then estimate of the pop. need to re-do with cars
</p>
</div>
<div class="figure" style="text-align: center"><span id="fig:bootexamsci"></span>
<img src="06-inference-num_files/figure-html/bootexamsci-1.png" alt="Histogram of differences in means after 1000 bootstrap samples from each of the two groups.  The observed difference is plotted as a black vertical line at 7.83.  The blue and green lines provide the percentile bootstrap and SE boostrap confidence intervals, respectively, for the difference in true population means." width="70%" />
<p class="caption">
Figure 6.26: Histogram of differences in means after 1000 bootstrap samples from each of the two groups. The observed difference is plotted as a black vertical line at 7.83. The blue and green lines provide the percentile bootstrap and SE boostrap confidence intervals, respectively, for the difference in true population means.
</p>
</div>

<div class="example">
<p>Choose one of the boostrap confidence intervals for the true difference in average pumping capacity, <span class="math inline">\(\mu_{esc} - \mu_{control}\)</span>. Does the interval show that there is a difference across the two treatments?</p>
<hr />
<p>Because the 90% intervals above do not overlap zero (zero is never one of the bootstrapped differences, 95% or 99% intervals would have given the same conclusion!), we conclude tha the ESC treatment is significantly better with respect to heart pumping capacity than the treatment.</p>
Beause the study is a randomized controled experiment, we can conclude that it is the treatment (ESC) whic is causing the change in pumping capacity.
</div>

</div>
</div>
<div id="mathematical-model-1" class="section level3">
<h3><span class="header-section-number">6.3.3</span> Mathematical model</h3>
<div id="t-test-for-mu_1---mu_2" class="section level4">
<h4><span class="header-section-number">6.3.3.1</span> <span class="math inline">\(t\)</span>-test for <span class="math inline">\(\mu_1 - \mu_2\)</span></h4>
<div id="observed-data-6" class="section level5 unnumbered">
<h5>Observed data</h5>
<p></p>
<p>A data set called <code>ncbirths</code> represents a random sample of 150 cases of mothers and their newborns in North Carolina over a year. Four cases from this data set are represented in Table <a href="inference-num.html#tab:babySmokeDF">6.7</a>. We are particularly interested in two variables: <code>weight</code> and <code>smoke</code>. The <code>weight</code> variable represents the weights of the newborns and the <code>smoke</code> variable describes which mothers smoked during pregnancy. We would like to know, is there convincing evidence that newborns from mothers who smoke have a different average birth weight than newborns from mothers who don’t smoke? We will use the North Carolina sample to try to answer this question. The smoking group includes 50 cases and the nonsmoking group contains 100 cases.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:babySmokeDF">Table 6.7: </span>Four cases from the <code>ncbirths</code> data set. The value <code>NA</code>, shown for the first two entries of the first variable, indicates that piece of data is missing.
</caption>
<thead>
<tr>
<th style="text-align:right;">
fage
</th>
<th style="text-align:right;">
mage
</th>
<th style="text-align:left;">
mature
</th>
<th style="text-align:right;">
weeks
</th>
<th style="text-align:left;">
premie
</th>
<th style="text-align:right;">
visits
</th>
<th style="text-align:left;">
marital
</th>
<th style="text-align:right;">
gained
</th>
<th style="text-align:right;">
weight
</th>
<th style="text-align:left;">
lowbirthweight
</th>
<th style="text-align:left;">
gender
</th>
<th style="text-align:left;">
habit
</th>
<th style="text-align:left;">
whitemom
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:left;">
younger mom
</td>
<td style="text-align:right;">
39
</td>
<td style="text-align:left;">
full term
</td>
<td style="text-align:right;">
10
</td>
<td style="text-align:left;">
not married
</td>
<td style="text-align:right;">
38
</td>
<td style="text-align:right;">
7.63
</td>
<td style="text-align:left;">
not low
</td>
<td style="text-align:left;">
male
</td>
<td style="text-align:left;">
nonsmoker
</td>
<td style="text-align:left;">
not white
</td>
</tr>
<tr>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:left;">
younger mom
</td>
<td style="text-align:right;">
42
</td>
<td style="text-align:left;">
full term
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:left;">
not married
</td>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
7.88
</td>
<td style="text-align:left;">
not low
</td>
<td style="text-align:left;">
male
</td>
<td style="text-align:left;">
nonsmoker
</td>
<td style="text-align:left;">
not white
</td>
</tr>
<tr>
<td style="text-align:right;">
19
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:left;">
younger mom
</td>
<td style="text-align:right;">
37
</td>
<td style="text-align:left;">
full term
</td>
<td style="text-align:right;">
11
</td>
<td style="text-align:left;">
not married
</td>
<td style="text-align:right;">
38
</td>
<td style="text-align:right;">
6.63
</td>
<td style="text-align:left;">
not low
</td>
<td style="text-align:left;">
female
</td>
<td style="text-align:left;">
nonsmoker
</td>
<td style="text-align:left;">
white
</td>
</tr>
<tr>
<td style="text-align:right;">
21
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:left;">
younger mom
</td>
<td style="text-align:right;">
41
</td>
<td style="text-align:left;">
full term
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:left;">
not married
</td>
<td style="text-align:right;">
34
</td>
<td style="text-align:right;">
8.00
</td>
<td style="text-align:left;">
not low
</td>
<td style="text-align:left;">
male
</td>
<td style="text-align:left;">
nonsmoker
</td>
<td style="text-align:left;">
white
</td>
</tr>
</tbody>
</table>

<div class="example">
<p>Set up appropriate hypotheses to evaluate
whether there is a relationship between a mother smoking
and average birth weight.</p>
<hr />
<p>The null hypothesis represents the case of no difference
between the groups.</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: There is no difference in average birth weight for
newborns from mothers who did and did not smoke.
In statistical notation: <span class="math inline">\(\mu_{n} - \mu_{s} = 0\)</span>,
where <span class="math inline">\(\mu_{n}\)</span> represents non-smoking mothers and
<span class="math inline">\(\mu_s\)</span> represents mothers who smoked.<br />
</li>
<li><span class="math inline">\(H_A\)</span>: There is some difference in average newborn weights
from mothers who did and did not smoke
(<span class="math inline">\(\mu_{n} - \mu_{s} \neq 0\)</span>).
</div></li>
</ul>
</div>
<div id="variability-of-the-statistic-6" class="section level5 unnumbered">
<h5>Variability of the statistic</h5>
<p>We check the two conditions necessary to model the difference
in sample means using the <span class="math inline">\(t\)</span>-distribution.</p>
<ul>
<li>Because the data come from a simple random sample,
the observations are independent,
both within and between samples.<br />
</li>
<li>With both data sets over 30 observations,
we inspect the data in
Figure <a href="inference-num.html#fig:babySmokePlotOfTwoGroupsToExamineSkew">6.27</a>
for any particularly extreme outliers
and find none.</li>
</ul>
<p>Since both conditions are satisfied, the difference
in sample means may be modeled using a <span class="math inline">\(t\)</span>-distribution.</p>
<div class="figure" style="text-align: center"><span id="fig:babySmokePlotOfTwoGroupsToExamineSkew"></span>
<img src="06-inference-num_files/figure-html/babySmokePlotOfTwoGroupsToExamineSkew-1.png" alt="The top panel represents birth weights for infants whose mothers smoked. The bottom panel represents the birth weights for infants whose mothers who did not smoke." width="70%" /><img src="06-inference-num_files/figure-html/babySmokePlotOfTwoGroupsToExamineSkew-2.png" alt="The top panel represents birth weights for infants whose mothers smoked. The bottom panel represents the birth weights for infants whose mothers who did not smoke." width="70%" />
<p class="caption">
Figure 6.27: The top panel represents birth weights for infants whose mothers smoked. The bottom panel represents the birth weights for infants whose mothers who did not smoke.
</p>
</div>

<div class="guidedpractice">
<p>The summary statistics in Table <a href="inference-num.html#tab:SumStatsBirthWeightNewbornsSmoke">6.8</a> may be useful
for this Guided Practice.<a href="#fn139" class="footnote-ref" id="fnref139"><sup>139</sup></a></p>
<ol style="list-style-type: lower-alpha">
<li>What is the point estimate of the population difference,
<span class="math inline">\(\mu_{n} - \mu_{s}\)</span>?</li>
<li>Compute the standard error of the point estimate from
part (a).
</div></li>
</ol>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:SumStatsBirthWeightNewbornsSmoke">Table 6.8: </span>Summary statistics for the <code>ncbirths</code> data set.
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
smoker
</th>
<th style="text-align:right;">
nonsmoker
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
mean
</td>
<td style="text-align:right;">
6.78
</td>
<td style="text-align:right;">
7.18
</td>
</tr>
<tr>
<td style="text-align:left;">
st. dev.
</td>
<td style="text-align:right;">
1.43
</td>
<td style="text-align:right;">
1.60
</td>
</tr>
<tr>
<td style="text-align:left;">
samp. size
</td>
<td style="text-align:right;">
50.00
</td>
<td style="text-align:right;">
100.00
</td>
</tr>
</tbody>
</table>
</div>
<div id="observed-statistic-vs.-null-statistics-3" class="section level5 unnumbered">
<h5>Observed statistic vs. null statistics</h5>

<div class="example">
<p>Complete the hypothesis test started in the previous Example and Guided Practice on <code>ncbirths</code> dataset and research question. Use a significance level of <span class="math inline">\(\alpha=0.05\)</span>.
For reference, <span class="math inline">\(\bar{x}_{n} - \bar{x}_{s} = 0.40\)</span>,
<span class="math inline">\(SE = 0.26\)</span>, and the sample sizes were <span class="math inline">\(n_n = 100\)</span>
and <span class="math inline">\(n_s = 50\)</span>.</p>
<hr />
<p>We can find the test statistic for this test
using the previous information:
<span class="math display">\[\begin{align*}
  T = \frac{\ 0.40 - 0\ }{0.26} = 1.54
  \end{align*}\]</span>
The p-value is represented by the two shaded tails
in Figure <a href="inference-num.html#fig:distOfDiffOfSampleMeansForBWOfBabySmokeData">6.28</a></p>
<p>We find the single tail area using software. We’ll use the
smaller of <span class="math inline">\(n_n - 1 = 99\)</span> and <span class="math inline">\(n_s - 1 = 49\)</span> as the
degrees of freedom: <span class="math inline">\(df = 49\)</span>.
The one tail area is 0.065;
doubling this value gives the two-tail area and p-value,
0.135.</p>
The p-value is larger than the significance value, 0.05,
so we do not reject the null hypothesis.
There is insufficient evidence to say there is a difference
in average birth weight of newborns from North Carolina mothers
who did smoke during pregnancy and newborns from North Carolina
mothers who did not smoke during pregnancy.
</div>

<div class="figure" style="text-align: center"><span id="fig:distOfDiffOfSampleMeansForBWOfBabySmokeData"></span>
<img src="06-inference-num_files/figure-html/distOfDiffOfSampleMeansForBWOfBabySmokeData-1.png" alt="The mathematical model for the T statistic when the null hypothesis is true.  As expected, the curve is centered at zero (the null value).  The observered statistic is also plotted with the area more extreme than the observed statistic plotted to indicate the p-value." width="70%" />
<p class="caption">
Figure 6.28: The mathematical model for the T statistic when the null hypothesis is true. As expected, the curve is centered at zero (the null value). The observered statistic is also plotted with the area more extreme than the observed statistic plotted to indicate the p-value.
</p>
</div>

<div class="guidedpractice">
We’ve seen much research suggesting smoking is harmful
during pregnancy, so how could we fail to reject the null
hypothesis in the previous Example?<a href="#fn140" class="footnote-ref" id="fnref140"><sup>140</sup></a>
</div>


<div class="guidedpractice">
If we made a Type 2 Error and there is a difference,
what could we have done differently in data collection
to be more likely to detect the difference?<a href="#fn141" class="footnote-ref" id="fnref141"><sup>141</sup></a>
</div>

<p>Public service announcement: while we have used this relatively
small data set as an example, larger data sets show that women
who smoke tend to have smaller newborns.
In fact, some in the tobacco industry actually had the audacity
to tout that as a <em>benefit</em> of smoking:</p>
<blockquote>
<p><em>It’s true.
The babies born from women who smoke are smaller,
but they’re just as healthy as the babies born from
women who do not smoke.
And some women would prefer having smaller babies.</em>
- Joseph Cullman, Philip Morris’ Chairman of the Board on CBS’ <em>Face the Nation</em>, Jan 3, 1971</p>
</blockquote>
<p>Fact check: the babies from women who smoke are not actually
as healthy as the babies from women who do not
smoke.<a href="#fn142" class="footnote-ref" id="fnref142"><sup>142</sup></a></p>
<!--
% Resource on this topic:
% http://archive.tobacco.org/Documents/documentquotes.html
-->
<p></p>
</div>
</div>
<div id="t-confidence-interval-for-mu_1---mu_2" class="section level4 unnumbered">
<h4><span class="math inline">\(t\)</span> confidence interval for <span class="math inline">\(\mu_1 - \mu_2\)</span></h4>
<div id="observed-data-7" class="section level5 unnumbered">
<h5>Observed data</h5>
<p>As with hypothesis testing, for the question of whether we can model the difference
using a <span class="math inline">\(t\)</span>-distribution, we’ll need to check new conditions.
Like the 2-proportion cases, we will require a more
robust version of independence so we are confident
the two groups are also independent.
Secondly, we also check for normality in each
group separately, which in practice is a check
for outliers.</p>
<p></p>
<!--
%\begin{examplewrap}
%\begin{nexample}{Set up hypotheses that will be used to test whether there is convincing evidence that ESCs actually increase the amount of blood the heart pumps. Also, check conditions for using the $t$-distribution for inference with the point estimate $\bar{x}_1 - \bar{x}_2$. To assist in this assessment, the data are presented in Figure \ref{stemCellTherapyForHearts}.}\label{exampleToEvaluteWhetherESCsAreHelpfulInImprovingHeartFunctionInSheep}
%We first setup the hypotheses:
%\begin{itemize}
%\setlength{\itemsep}{0mm}
%\item[$H_0$:] The stem cells do not improve heart pumping function. $\mu_{esc} - \mu_{control} = 0$.
%\item[$H_A$:] The stem cells do improve heart pumping function. $\mu_{esc} - \mu_{control} > 0$.
%\end{itemize}
%\end{nexample}
%\end{examplewrap}
-->

<div class="onebox">
<p><strong>Using the <span class="math inline">\(t\)</span>-distribution for a difference in means.</strong></p>
<p>The <span class="math inline">\(t\)</span>-distribution can be used for inference when working
with the standardized difference of two means if</p>
<ul>
<li><em>Independence</em> (extended).
The data are independent within and between
the two groups, e.g., the data come from
independent random samples or from a
randomized experiment.<br />
</li>
<li><em>Normality</em>.
We check the outliers for
each group separately.</li>
</ul>
<p>The standard error may be computed as
<span class="math display">\[\begin{align*}
  SE
    = \sqrt{\frac{\sigma_1^2}{n_1} + \frac{\sigma_2^2}{n_2}}
  \end{align*}\]</span></p>
The official formula for the degrees of freedom is quite
complex and is generally computed using software,
so instead you may use the smaller of
<span class="math inline">\(n_1 - 1\)</span> and <span class="math inline">\(n_2 - 1\)</span> for the degrees of freedom
if software isn’t readily available.
</div>

<p></p>
</div>
<div id="variability-of-the-statistic-7" class="section level5 unnumbered">
<h5>Variability of the statistic</h5>

<div class="example">
<p>Can the <span class="math inline">\(t\)</span>-distribution be used to make
inference using the point estimate,
<span class="math inline">\(\bar{x}_{esc} - \bar{x}_{control} = 7.83\)</span>?</p>
<hr />
<p>First, we check for independence.
Because the sheep were randomized into
the groups, independence within
and between groups is satisfied.</p>
<p>Figure <a href="inference-num.html#fig:stemCellTherapyForHearts">6.29</a>
does not reveal any clear outliers
in either group.
(The ESC group does look a bit more variability,
but this is not the same as having clear outliers.)</p>
With both conditions met, we can use the
<span class="math inline">\(t\)</span>-distribution to model the difference of sample means.
</div>

<div class="figure" style="text-align: center"><span id="fig:stemCellTherapyForHearts"></span>
<img src="06-inference-num_files/figure-html/stemCellTherapyForHearts-1.png" alt="Histograms for both the embryonic stem cell and control group." width="70%" /><img src="06-inference-num_files/figure-html/stemCellTherapyForHearts-2.png" alt="Histograms for both the embryonic stem cell and control group." width="70%" />
<p class="caption">
Figure 6.29: Histograms for both the embryonic stem cell and control group.
</p>
</div>
<p>Generally, we use statistical software to find the appropriate
degrees of freedom, or if software isn’t available,
we can use the smaller
of <span class="math inline">\(n_1 - 1\)</span> and <span class="math inline">\(n_2 - 1\)</span> for the degrees of freedom,
e.g., if using a <span class="math inline">\(t\)</span>-table to find tail areas.
For transparency in the Examples and Guided Practice,
we’ll use the latter approach for finding <span class="math inline">\(df\)</span>;
in the case of the ESC example, this means we’ll use <span class="math inline">\(df = 8\)</span>.</p>

<div class="example">
<p>Calculate a 95% confidence interval for the
effect of ESCs on the change in heart pumping capacity of
sheep after they’ve suffered a heart attack.</p>
<hr />
We will use the sample difference and the standard error that
we computed earlier calculations:
<span class="math display">\[\begin{align*}
  \bar{x}_{esc} - \bar{x}_{control} = 7.83
  &amp;&amp; SE = \sqrt{\frac{5.17^2}{9} + \frac{2.76^2}{9}} = 1.95
  \end{align*}\]</span>
Using <span class="math inline">\(df = 8\)</span>, we can identify the
multiplier of <span class="math inline">\(t^{\star}_{8} = 2.31\)</span>
for a 95% confidence interval.
Finally, we can enter the values into the confidence
interval formula:
<span class="math display">\[\begin{align*}
  \text{point estimate} \ \pm\ t^{\star} \times SE
    \quad\rightarrow\quad 7.83 \ \pm\ 2.31\times 1.95
    \quad\rightarrow\quad (3.32, 12.34)
  \end{align*}\]</span>
We are 95% confident that embryonic stem cells improve
the heart’s pumping function in sheep that have suffered
a heart attack by 3.32% to 12.34% .
</div>

<p></p>
<!--
As with past statistical inference applications,
there is a well-trodden procedure.
\begin{description}
\setlength{\itemsep}{0mm}
\item[Prepare.]
    Retrieve critical contextual information,
    and if appropriate, set up hypotheses.
\item[Check.]
    Ensure the required conditions are reasonably
    satisfied.
\item[Calculate.]
    Find the standard error, and then construct
    a confidence interval, or if conducting
    a hypothesis test, find a test statistic
    and p-value.
\item[Conclude.]
    Interpret the results in the context of the
    application.
\end{description}
The details change a little from one setting to the next,
but this general approach remain the same.

-->
</div>
</div>
</div>
</div>
<div id="summary-of-t-procedures" class="section level2">
<h2><span class="header-section-number">6.4</span> Summary of t-procedures</h2>
<p>So far in this chapter, we have seen the <span class="math inline">\(t\)</span>-distribution applied as the appropriate mathematical model in three distinct settings. Although the three data structures are different, their similarities and differences are worth pointing out. We provide Table <a href="inference-num.html#tab:tcompare">6.9</a> partly as a mechanism for understanding <span class="math inline">\(t\)</span>-procedures and partly to highlight the extremely common usage of the <span class="math inline">\(t\)</span>-distribution in practice. You will often hear the following three <span class="math inline">\(t\)</span>-procedures referred to as a <strong>one sample <span class="math inline">\(t\)</span>-test</strong> (<span class="math inline">\(t\)</span>-interval), <strong>paired <span class="math inline">\(t\)</span>-test</strong> (<span class="math inline">\(t\)</span>-interval), and <strong>two sample <span class="math inline">\(t\)</span>-test</strong> (<span class="math inline">\(t\)</span>-interval).</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:tcompare">Table 6.9: </span>Similarities of <span class="math inline">\(t\)</span>-methods across one sample, paired sample, and two independent samples analysis of a numeric response variable.
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
one sample
</th>
<th style="text-align:left;">
paired sample
</th>
<th style="text-align:left;">
two indep. samples
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
response variable
</td>
<td style="text-align:left;">
numeric
</td>
<td style="text-align:left;">
numeric
</td>
<td style="text-align:left;">
numeric
</td>
</tr>
<tr>
<td style="text-align:left;">
explanatory variable
</td>
<td style="text-align:left;">
none
</td>
<td style="text-align:left;">
binary
</td>
<td style="text-align:left;">
binary
</td>
</tr>
<tr>
<td style="text-align:left;">
parameter of interest
</td>
<td style="text-align:left;">
mean: <span class="math inline">\(\mu\)</span>
</td>
<td style="text-align:left;">
paired mean diff: <span class="math inline">\(\mu_{diff}\)</span>
</td>
<td style="text-align:left;">
diff in means: <span class="math inline">\(\mu_1 - \mu_2\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
statistic of interest
</td>
<td style="text-align:left;">
mean: <span class="math inline">\(\bar{x}\)</span>
</td>
<td style="text-align:left;">
paired mean diff: <span class="math inline">\(\bar{x}_{diff}\)</span>
</td>
<td style="text-align:left;">
diff in means: <span class="math inline">\(\bar{x}_1 - \bar{x}_2\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
standard error
</td>
<td style="text-align:left;">
<span class="math inline">\(\frac{s}{\sqrt{n}}\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\frac{s_{diff}}{\sqrt{n_{diff}}}\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\sqrt{\frac{s_1^2}{n_1} + \frac{s_2^2}{n_2}}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
degrees of freedom
</td>
<td style="text-align:left;">
<span class="math inline">\(n-1\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(n_{diff} -1\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\min(n_1 -1, n_2 - 1)\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
conditions
</td>
<td style="text-align:left;">
<ol style="list-style-type: decimal">
<li>independence, 2. normality or large samples
</td>
<td style="text-align:left;">
<ol style="list-style-type: decimal">
<li>independence, 2. normality or large samples
</td>
<td style="text-align:left;">
<ol style="list-style-type: decimal">
<li>independence, 2. normality or large samples
</td>
</tr>
</tbody>
</table></li>
</ol></li>
</ol></li>
</ol>
<p><strong>Hypothesis tests.</strong> When applying the <span class="math inline">\(t\)</span>-distribution for a hypothesis test, we proceed as follows:</p>
<ol style="list-style-type: decimal">
<li>Write appropriate hypotheses.<br />
</li>
<li>Verify conditions for using the <span class="math inline">\(t\)</span>-distribution.
<ul>
<li>One-sample or differences from paired data: the observations (or differences) must be independent and nearly normal. For larger sample sizes, we can relax the nearly normal requirement, e.g., slight skew is okay for sample sizes of 15, moderate skew for sample sizes of 30, and strong skew for sample sizes of 60.<br />
</li>
<li>For a difference of means when the data are not paired: each sample mean must separately satisfy the one-sample conditions for the <span class="math inline">\(t\)</span>-distribution, and the data in the groups must also be independent.</li>
</ul></li>
<li>Compute the statistic of interest, the standard error, and the degrees of freedom. For <span class="math inline">\(df\)</span>, use <span class="math inline">\(n-1\)</span> for one sample, and for two samples use either statistical software or the smaller of <span class="math inline">\(n_1 - 1\)</span> and <span class="math inline">\(n_2 - 1\)</span>.<br />
</li>
<li>Compute the T-score using the general formula:
<span class="math display">\[
 T = \frac{\mbox{statistic} - \mbox{null value}}{\mbox{standard error}}
 \]</span></li>
<li>Use the statistical software to find the p-value using the appropriate <span class="math inline">\(t\)</span>-distribution:
<ul>
<li>Sign in <span class="math inline">\(H_a\)</span> is <span class="math inline">\(&lt;\)</span>: p-value = area below T-score</li>
<li>Sign in <span class="math inline">\(H_a\)</span> is <span class="math inline">\(&gt;\)</span>: p-value = area above T-score</li>
<li>Sign in <span class="math inline">\(H_a\)</span> is <span class="math inline">\(\neq\)</span>: p-value = 2 <span class="math inline">\(\times\)</span> area below <span class="math inline">\(-|\mbox{T-score}|\)</span></li>
</ul></li>
<li>Make a conclusion based on the p-value, and write a conclusion in context, in plain language, and in terms of the alternative hypothesis.</li>
</ol>
<p><strong>Confidence intervals.</strong> Similarly, the following is how we generally computed a confidence interval using a <span class="math inline">\(t\)</span>-distribution:</p>
<ol style="list-style-type: decimal">
<li>Verify conditions for using the <span class="math inline">\(t\)</span>-distribution. (See above.)<br />
</li>
<li>Compute the point estimate of interest, the standard error, the degrees of freedom, and <span class="math inline">\(t^{\star}_{df}\)</span>.<br />
</li>
<li>Calculate the confidence interval using the general formula:
<span class="math display">\[
 \mbox{statistic} \pm\ t_{df}^{\star} SE.
 \]</span></li>
<li>Put the conclusions in context and in plain language so even non-data scientists can understand the results.</li>
</ol>
</div>
<div id="r-inference-for-quantitative-data" class="section level2">
<h2><span class="header-section-number">6.5</span> <code>R</code>: Inference for quantitative data</h2>

<div class="todo">
Section on doing inference for categorical data in R.
- Simulation functions in catstats
- <code>t.test</code>
</div>

<div id="interactive-r-tutorials" class="section level3">
<h3><span class="header-section-number">6.5.1</span> Interactive R tutorials</h3>
<p>Navigate the concepts you’ve learned in this chapter in R using the following self-paced tutorials.
All you need is your browser to get started!</p>
<div class="alltutorials">
<p><a href="https://openintrostat.github.io/ims-tutorials/07-inference-for-numerical-responses/">Tutorial 7: Inference for categorical responses</a></p>
</div>
<div class="singletutorial">
<p><a href="https://openintro.shinyapps.io/ims-07-inference-for-numerical-responses-01/">Tutorial 7 - Lesson 1: Bootstrapping for estimating a parameter</a></p>
</div>
<div class="singletutorial">
<p><a href="https://openintro.shinyapps.io/ims-07-inference-for-numerical-responses-02/">Tutorial 7 - Lesson 2: Introducing the t-distribution</a></p>
</div>
<div class="singletutorial">
<p><a href="https://openintro.shinyapps.io/ims-07-inference-for-numerical-responses-03/">Tutorial 7 - Lesson 3: Inference for difference in two means</a></p>
</div>
<div class="singletutorial">
<p><a href="https://openintro.shinyapps.io/ims-07-inference-for-numerical-responses-04/">Tutorial 7 - Lesson 4: Comparing many means</a></p>
</div>
<p>You can also access the full list of tutorials supporting this book <a href="https://openintrostat.github.io/ims-tutorials/">here</a>.</p>
</div>
<div id="r-labs" class="section level3">
<h3><span class="header-section-number">6.5.2</span> R labs</h3>
<p>Further apply the concepts you’ve learned in this chapter in R with computational labs that walk you through a data analysis case study.</p>
<div class="singlelab">
<p><a href="http://openintrostat.github.io/oilabs-tidy/07_inf_for_numerical_data/inf_for_numerical_data.html">Inference for numerical responses - Youth Risk Behavior Surveillance System</a></p>
</div>
<div class="alllabs">
<p><a href="http://openintrostat.github.io/oilabs-tidy/">Full list of labs supporting OpenIntro::Introduction to Modern Statistics</a></p>
</div>
</div>
</div>
<div id="chp6-review" class="section level2">
<h2><span class="header-section-number">6.6</span> Chapter 6 review</h2>
<div id="terms" class="section level3">
<h3><span class="header-section-number">6.6.1</span> Terms</h3>
<p>We introduced the following terms in the chapter.
If you’re not sure what some of these terms mean, we recommend you go back in the text and review their definitions.
We are purposefully presenting them in alphabetical order, instead of in order of appearance, so they will be a little more challenging to locate.
However you should be able to easily spot them as <strong>bolded text</strong>.</p>
<table>
<tbody>
<tr>
<td style="text-align:left;">
bootstrapping
</td>
<td style="text-align:left;">
one sample <span class="math inline">\(t\)</span>-test
</td>
<td style="text-align:left;">
point estimate
</td>
<td style="text-align:left;">
two sample <span class="math inline">\(t\)</span>-test
</td>
</tr>
<tr>
<td style="text-align:left;">
Central Limit Theorem
</td>
<td style="text-align:left;">
paired <span class="math inline">\(t\)</span>-test
</td>
<td style="text-align:left;">
t-distribution
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
degrees of freedom
</td>
<td style="text-align:left;">
paired data
</td>
<td style="text-align:left;">
T score
</td>
<td style="text-align:left;">
</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="129">
<li id="fn129"><p>The the middle 95% of a distribution would range from the 2.5th percentile (the value with 2.5% of the distribution below) to the 97.5th percentile (the value with 2.5% of the distribution above). <a href="inference-num.html#fnref129" class="footnote-back">↩︎</a></p></li>
<li id="fn130"><p>More
nuanced guidelines would consider further relaxing
the <em>particularly extreme outlier</em> check when the
sample size is very large.
However, we’ll leave further discussion here to a future course.<a href="inference-num.html#fnref130" class="footnote-back">↩︎</a></p></li>
<li id="fn131"><p>We want to find the shaded area <em>above</em> -1.79 (we leave the picture to you).
The lower tail area has an area of 0.0447,
so the upper area would have an area of <span class="math inline">\(1 - 0.0447 = 0.9553\)</span>.<a href="inference-num.html#fnref131" class="footnote-back">↩︎</a></p></li>
<li id="fn132"><p>The sample size is under 30,
so we check for obvious outliers:
since all observations are within 2 standard deviations
of the mean, there are no such clear outliers.<a href="inference-num.html#fnref132" class="footnote-back">↩︎</a></p></li>
<li id="fn133"><p><span class="math inline">\(\bar{x} \ \pm\ t^{\star}_{14} \times SE  \ \to\  0.287 \ \pm\  1.76 \times 0.0178  \ \to\ (0.256, 0.318)\)</span>.
We are 90% confident that the average mercury content
of croaker white fish (Pacific) is between 0.256 and 0.318 ppm.<a href="inference-num.html#fnref133" class="footnote-back">↩︎</a></p></li>
<li id="fn134"><p>No, a confidence interval only provides a range
of plausible values for a population parameter,
in this case the population mean.
It does not describe what we might observe
for individual observations.<a href="inference-num.html#fnref134" class="footnote-back">↩︎</a></p></li>
<li id="fn135"><p><span class="math inline">\(H_0\)</span>: The average 10-mile run time was the same for 2006 and 2017. <span class="math inline">\(\mu = 93.29\)</span> minutes. <span class="math inline">\(H_A\)</span>: The average 10-mile run time for 2017 was <em>different</em> than that of 2006. <span class="math inline">\(\mu \neq 93.29\)</span> minutes.<a href="inference-num.html#fnref135" class="footnote-back">↩︎</a></p></li>
<li id="fn136"><p>With a sample of 100,
we should only be concerned if there is are particularly
extreme outliers.
The histogram of the data doesn’t show any outliers of concern
(and arguably, no outliers at all).<a href="inference-num.html#fnref136" class="footnote-back">↩︎</a></p></li>
<li id="fn137"><p><span class="math inline">\(H_0\)</span>: the exams are equally difficult, on average. <span class="math inline">\(\mu_A - \mu_B = 0\)</span>. <span class="math inline">\(H_A\)</span>: one exam was more difficult than the other, on average. <span class="math inline">\(\mu_A - \mu_B \neq 0\)</span>.<a href="inference-num.html#fnref137" class="footnote-back">↩︎</a></p></li>
<li id="fn138"><p>
(a) Since the exams were shuffled,
the “treatment” in this case was randomly assigned,
so independence within and between groups is satisfied.
(b) The summary statistics suggest the data are roughly
symmetric about the mean, and the min/max values don’t
suggest any outliers of concern.<a href="inference-num.html#fnref138" class="footnote-back">↩︎</a></p></li>
<li id="fn139"><p>(a) The difference in sample means is an
appropriate point estimate: <span class="math inline">\(\bar{x}_{n} - \bar{x}_{s} = 0.40\)</span>.
(b) The standard error of the estimate can be
calculated using the standard error formula:
<span class="math display">\[\begin{align*}
  SE
    = \sqrt{\frac{\sigma_n^2}{n_n} + \frac{\sigma_s^2}{n_s}}
      \approx \sqrt{\frac{s_n^2}{n_n} + \frac{s_s^2}{n_s}}
    = \sqrt{\frac{1.60^2}{100} + \frac{1.43^2}{50}}
    = 0.26
  \end{align*}\]</span><a href="inference-num.html#fnref139" class="footnote-back">↩︎</a></p></li>
<li id="fn140"><p>It is possible that there is a difference
but we did not detect it.
If there is a difference, we made a Type 2 Error.<a href="inference-num.html#fnref140" class="footnote-back">↩︎</a></p></li>
<li id="fn141"><p>We could have collected more data.
If the sample sizes are larger, we tend to have
a better shot at finding a difference if one exists.
In fact, this is exactly what we would find if we
examined a larger data set!<a href="inference-num.html#fnref141" class="footnote-back">↩︎</a></p></li>
<li id="fn142"><p>You can watch an episode of John Oliver
on <a href="youtu.be/6UsHHOCH4q8"><em>Last Week Tonight</em></a> to explore the present day
offenses of the tobacco industry.
Please be aware that there is some adult language.<a href="inference-num.html#fnref142" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="inference-cat.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="inference-reg.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": false,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/MTstateIntroStats/IntroStatTextbook/edit/master/06-inference-num.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["stat216-textbook.pdf"],
"toc": {
"collapse": "subsection",
"toc_depth": 4,
"toc_float": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
